### ISSUE TITLE
Calling `done` after test has completed

### ISSUE THREAD

**Issue by flore77** [qunitjs/qunit#1019]
While working to integrate JsReporters into [browserstack-runner](https://github.com/browserstack/browserstack-runner/issues/157), I got in some problems with tests that were including async operations, while each framework is treating this different.

Qunit provides async contro throughl: `async( [acceptCallCount ] ), Type: Number, acceptCallCount (default: 1)`

But Qunit will fail a test only if the callback returned by assert.async() will be called **synchronus** more times than acceptCallCount.

Example:

``` js
// QUnit will report this test as failed
test('aa', function(assert) {
  var done = assert.async();
  assert.ok(true);
  done();
  done();
});

// QUnit will report this test as passed
test('aa', function(assert) {
    var done = assert.async();
    assert.ok(true);
    done();
    setTimeout(function() {
      done();
    }, 1000);
});
```

Mocha would have failed both tests.

Jasmine would have report both tests as passed.

The difference between Mocha and QUnit is that Mocha emits the test twice, one time as passed, the other time as failed when the `done` callback is called the second time, on the other hand QUnit emits the test only one time.

We on the JsReporters would want to set a standard for this so I and also @jzaefferer have agreed that a **single emit** for the failure seems correct. But I don't know how it can be achieved. For the above example with the passing test (which theoretically should be failing), the done callback is called and Qunit thinks everything is ok, this test has passed, but it will not know if the done callback will be called a second time, it would have to wait for an indefinite period of time. If I set the timeout to be after 5 minutes, but after 10 minutes etc.

What's your opinion about this? Do you agree that it should be a single emit ? Or do you find that how Mocha proceeds is right? Should we treat the above example like a bug in the test itself and QUnit should have nothing to do with it?

**Comment by gibson042** [comment]
I think there's a case to be made that the QUnit single-emit approach is appropriate, but Mocha's multiple-emit is better IMHO (albeit more work to report and to process). But both should be considered acceptable, since as you point out the test itself is the real problem.

**Comment by trentmwillis** [comment]
> a **single emit** for the failure seems correct.

I don't see how it would be possible to make a single-emit model catch the failure as you have no idea at what point a failure might occur (as you point out), could be an inordinate amount of time in the future.

That said, I don't think swallowing the error (like QUnit currently does) is good either as the feedback from the multi-emit strategy of Mocha provides the developer with more information about their test.

Since the test is the real problem I tend to think  we don't necessarily need to change QUnit's behavior but I am also not against giving more information back to developers.

**Comment by flore77** [comment]
> albeit more work to report and to process

Yes, indeed. Also I think to multiple-emit, maybe js-reporters should introduce a new event, especially for this case, because currently their exits only 2 events `testStart` and `testEnd`, and to mutiple-emit a test end twice seems a little bit confusing, in my opinion.

> I am also not against giving more information back to developers.

I'm thinking that Jasmine does not provide any feedback, it does not care if the done callback is called multiple times and still it is used by a lot of people, so I am wondering how many people would gain something if we use a multi-emit strategy.

**Comment by jzaefferer** [comment]
A test with multiple `done()` calls like described above should be considered buggy by the test framework, and throw some kind of error to alert the developer to the bug. That said, I see no reason to accommodate that buggy behaviour in the reporter, e.g. with a special event.

**Comment by platinumazure** [comment]
Worth noting that I have attempted to use static analysis for the opposite problem (async call is not obviously resolved in the test) in [a rule](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/resolve-async.md) in my [QUnit ESLint plugin](https://github.com/platinumazure/eslint-plugin-qunit). I could certainly try to extend the rule to flag the other cases.

That doesn't solve the immediate problem, but it might allow for a less "user-friendly" stance if we can say that there exists tooling to help catch these at other stages of the build process. (Although said tooling doesn't exist just yet, I suppose.)

**Comment by flore77** [comment]
> I see no reason to accommodate that buggy behaviour in the reporter

Agree.

I wanted to make a point that maybe it is not worth to bother so much by failing tests if the `done` callback is called multiple times, like Jasmine does, maybe some other tools could do that, like @platinumazure pointed out in the above comment.

Anyway at least the documentation should be updated that Qunit will fail a test only if the callback returned by assert.async() will be called synchronus more times than acceptCallCount.

**Comment by jzaefferer** [comment]
> I wanted to make a point that maybe it is not worth to bother so much by failing tests if the done callback is called multiple times, like Jasmine does

That shouldn't be a big deal for QUnit either. We have a mechanism in place to handle errors that are thrown outside of a running test. Calling an already resolved `done()` callback should have similar behaviour.

**Comment by trentmwillis** [comment]
I just looked into this a bit myself, it looks like we do log a failing assertion, but it would be up to the reporter to know what to do with the failure and report it as such:

![screen shot 2017-04-05 at 10 17 28 am](https://cloud.githubusercontent.com/assets/3526753/24717998/41cdb4dc-19e9-11e7-8867-dc9805024624.png)

I think **revising this behavior to throw an actual error** when called outside the associated test would be best, so that it is not up to the reporter to handle weird behavior.

**Comment by leobalter** [comment]
Sometimes I wonder if we gave too much responsibility to `assert.async()` setting a max number of calls.

If I could I would reuse it as a promise resolver and not setting some max amount.

Maybe we can handle this with generators where every `done` call for `var done = assert.async();` would call a `next()` and anything further than that would trigger an error.

Drafting:

```js
function* gen(n = 1) {
    yield* new Array(n - 1);
}

var async = n => {
	var iter = gen(n);
    var completed;
	
	return () => {
		if (completed) { throw Error('done called more than expected') }
		completed = iter.next().done;
    };
}
```

Experimenting the draft:

```js
var done = async();

done()

var test = false;
try {
  done()
} catch(e) {
  test = true;
} finally {
  console.log('test 1:', test);
}

var done = async(2);

done()
done()

test = false;
try {
  done()
} catch(e) {
  test = true;
} finally {
  console.log('test 2:', test);
}

var done = async(3);

done()
done()
done()

test = false;
try {
  done()
} catch(e) {
  test = true;
} finally {
  console.log('test 3:', test);
}
```

**Comment by leobalter** [comment]
turns out there's no need to use a generator at all: 

```js
var async = (n = 1) => {
	var arr = new Array(n);
    var completed;
	
	return () => {
		if (completed) { throw Error('done called more than expected') }
		arr.pop();
		completed = !arr.length;
    };
}
```

**Comment by leobalter** [comment]
Here's me, without my daily coffee bikesheding in a useless thing.

The approach I suggested is already the one used for async, using a number value instead of an Array, because it's even better.

**Comment by trentmwillis** [comment]
@leobalter seems like an interesting train of thought for the future, but tangential to the current issue I think.
