### ISSUE TITLE
feature: Make it possible to load QUnit after domReady

### ISSUE THREAD

**Issue by TobiasOetzel** [qunitjs/qunit#1059]
I am using QUnit together with [OpenUI5](https://github.com/SAP/openui5)

UI5 comes with its own amd syntax similar to require.js.

It would be nice to be able to load QUnit asynchronously to provide a test environment from the framework side.

How i would imagine it is that you could define a global QUnit config before QUnit itself is loaded

`
window.QUnit = {
  config: {
    autostart: false
  }
};
`

When QUnit is loaded, it takes this config and extends it with the needed defaults. Here is a full [jsbin](http://jsbin.com/fewake/1/edit?html,js,output) outlining the problem

If you like the idea i would create a pull request for it. I just wanted to discuss it upfront.

**Comment by platinumazure** [comment]
@TobiasOetzel I use QUnit with RequireJS at my workplace, and we're able to stop the test runner from executing prematurely with this code:

```js
QUnit.config.autostart = false;

require(['path/to/tests'], function () {
    QUnit.start();
});
```

In your JSBin, I do see the test being executed. Can you please explain the exact issue? Is the test starting too soon?

**Comment by trentmwillis** [comment]
Didn't dig into the example at this moment, but want to mention that this sounds similar to a suggestion brought up in https://github.com/jonkemp/qunit-phantomjs-runner/issues/11#issuecomment-230063369.

**Comment by TobiasOetzel** [comment]
@platinumazure 
Yes there is [extra code](https://github.com/jquery/qunit/blob/master/src/export.js#L95) for amd syntax in QUnit setting autostart to another default. That would be a trick to define the ducktype before loading QUnit.

@trentmwillis Yes this looks exactly like the issue you pointed to. How is the state of the discussion? I saw some extra phantomJS code.

**Comment by trentmwillis** [comment]
No movement really, left off with needing to define an API for it.
