### ISSUE TITLE
Should we extract src/core/onerror.js core logic to be independent of browser?

### ISSUE THREAD

**Issue by platinumazure** [qunitjs/qunit#1061]
Can we extract the [core logic](https://github.com/jquery/qunit/blob/904e389d85232a9d6d783881e879fce9a0965b3f/src/core/onerror.js#L28-L38) of src/core/onerror into a module, and then change the HTML reporter (or other browser-specific orchestration code) to expose a wrapper of that code as `window.onerror`?

This would allow me to use that same logic pretty easily in similar-but-not-quite-equivalent scenarios, such as `require.onError` when using RequireJS.

As a bonus, this may prevent the need for #1051 (at least for me). Or, at the very least, it will allow us to have a purer API there (right now I'm trying to solve a few different problems with that PR).

**Comment by platinumazure** [comment]
Ping @Krinkle @JamesMGreene, since both of you inspired me to look in this direction.

**Comment by JamesMGreene** [comment]
Should also probably roll in handling `process.on( 'uncaughtException', function( err ) { ... } );` when running on Node.js, and any other CommonJS/Rhino/Nashorn error handling as makes sense.

**Comment by JamesMGreene** [comment]
Our current `window.onerror` handler also does not attempt to utilize the modern signature, which provides 5 arguments (the last being the actual `Error` object).

**Comment by leobalter** [comment]
I'm +1 to seek a solution using `process.on( 'uncaughtException', ...` and a modern event listener to replace window.onerror, addEventListener is a valid option after QUnit 2

**Comment by platinumazure** [comment]
Fixed by baff17d.
