### ISSUE TITLE
Remove JSHint/JSCS leftovers

### ISSUE THREAD

**Issue by mgol** [qunitjs/qunit#1066]
I've noticed the repo still has some JSHint/JSCS leftovers - config files, pragma comments etc. They should all be removed now that the repo has migrated to ESLint.

**Comment by platinumazure** [comment]
Oops, guess I missed some of those. Agreed, and I'll investigate in the next couple of days (but if anyone wants to submit a PR, feel free).

**Comment by kumarmj** [comment]
Hello I will be happy to submit a PR, if I am not wrong I need to 

- [ ] Delete [jshintrc](https://github.com/qunitjs/qunit/blob/master/.jshintrc) config file
- [ ] Remove these pragma comments [src/equiv.js#L16](https://github.com/qunitjs/qunit/blob/master/src/equiv.js#L16)  [main/assert.js#L251](https://github.com/qunitjs/qunit/blob/master/test/main/assert.js#L251) [main/assert.js#L257](https://github.com/qunitjs/qunit/blob/master/test/main/assert.js#L257)

**Comment by platinumazure** [comment]
That should cover the JSHint artifacts, but we also need to cover JSCS as well. Looking forward to your PR!

One other thought- you could use ESLint's "no-warning-comments" rule to try to identify other JSHint or JSCS comments in code, to make sure nothing else is missed.

**Comment by kumarmj** [comment]
@platinumazure updated above comment for `jscsrc`, but I did not found any JSCS comments. Sending a PR please review.
