### ISSUE TITLE
Run tests on Node 7 (& perhaps stop on 0.10?)

### ISSUE THREAD

**Issue by mgol** [qunitjs/qunit#1067]
Node 7 is stable so QUnit should be tested on it. OTH, upstream support for Node 0.10 has just ended so it might be good to plan when to drop it.

jQuery Core has already stopped testing on Node 0.10 but we're in a different situation than QUnit.

**Comment by trentmwillis** [comment]
This sounds good to me. We've discussed before, but I would like our support policy for Node to essentially be LTS + Current Stable.

**Comment by mgol** [comment]
Which LTS, though? Those in Active or Maintenance mode? Note the following at https://github.com/nodejs/LTS/#node-abstraction-layer:
> It should be stated that the abstraction layer (currently NAN) should support all current LTS releases. Given that Active LTS will overlap for a period of 6 months, this means that the abstraction layer will, at any given point in time, fully support a maximum of 2 LTS releases.

(by _current_ they mean Active here)

It seems you mean the Active ones then (1 or 2 at a time), is that true?

**Comment by trentmwillis** [comment]
I would actually not be opposed to including both Active and Maintenance LTS versions. Ideally the fewer version we have to track is helpful as maintainers, but if the Maintenance LTS is likely to still have heavy usage (as I suspect), then we should likely continue to support it.

**Comment by mgol** [comment]
@trentmwillis it makes sense, although, as I mentioned before, NAN plans to only support Active LTS and not Maintenance ones so if QUnit needed any native dependencies from npm then it might not be possible to support the old & new versions simultaneously.

But it's all theoretical for now - let's keep that potential problem in mind but we'll deal with it once it manifests itself for real.
