### ISSUE TITLE
Not 'loading' properly on Node

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#1081]
We need to make this more friendly on Node. 

@getify helped me finding this bug.

As you can see [here](https://github.com/qunitjs/qunit/blob/master/build/tasks/test-on-node.js#L54-L55), unless we call `QUnit.load()` before `QUnit.start()`, QUnit won't run properly in Node.

We need to make `QUnit.start` a self method to _load_ and start QUnit without calling anything else. This is the expected behavior reading the api docs.

The good part is that we can remove any sights of 1.x warnings of QUnit.start along.

---

As I can't commit to any code today, I'm planning to fix this tomorrow - Dec 12 - in the evening (EST), high priority, unless someone wants to fix it before, please just add a comment here.

**Comment by getify** [comment]
Will this be in a patch release (2.1.1)? Any ETA?

**Comment by leobalter** [comment]
Yes, this week.
