### ISSUE TITLE
Test runner UI checkbox settings not synced with query parameters

### ISSUE THREAD

**Issue by etseidler** [qunitjs/qunit#1082]
When specifying values for the test runner's query params they aren't synced up to the checkboxes for the corresponding settings.  This affects the hidepassed query param more than the others, because the functionality is directly tied to the box being checked as opposed to the presence of the query param itself.

This problem can be replicated using [the basic example](http://qunitjs.com/cookbook/#automating-unit-testing) and was happening in multiple browsers on multiple platforms. After creating the HTML file, open the file in a browser. When using version 2.0.1 of QUnit, the checkboxes are synced up correctly with the query parameters. When using version 2.1.0 of QUnit, the syncing doesn't work the same way. For example, when using 2.1.0, select the 'Hide Passed Tests' checkbox, then refresh the page. The checked value is lost. Selecting the 'No try-catch' will immediately refresh the page, and will drop the checked value of that checkbox as part of the refresh.

**Comment by trentmwillis** [comment]
Thanks for reporting! I can reproduce this on my local development copy of QUnit as well. Definitely a bug.

If you could try to figure out what's wrong and open a PR it would be greatly appreciated!

**Comment by etseidler** [comment]
the problem seems to have been introduced in https://github.com/qunitjs/qunit/commit/80a14ee5ac49c7f0981884a6cbb5786dea3a9c8b
