### ISSUE TITLE
QUnit 2.x cannot be run in a sandboxed iframe due to direct reference to window.sessionStorage

### ISSUE THREAD

**Issue by Gaurav0** [qunitjs/qunit#1090]
See https://github.com/ember-cli/ember-twiddle/issues/516

**Comment by rwjblue** [comment]
Thanks for opening @Gaurav0, hopefully some of the core devs can chime in and confirm if this was intentional...

**Comment by trentmwillis** [comment]
We did some refactoring to introduce `config.storage` recently, so likely either https://github.com/qunitjs/qunit/pull/1042 or https://github.com/qunitjs/qunit/pull/1055. Definitely a bug; @Gaurav0 if you have time, would you mind digging in and trying to figure out what's wrong?
