### ISSUE TITLE
Augment QUnit Cookbook to show off Step API

### ISSUE THREAD

**Issue by platinumazure** [qunitjs/qunit#1100]
Per [this comment](https://github.com/qunitjs/qunit/issues/1075#issuecomment-275149846), we should see if we can augment the QUnit Cookbook with a case study on the Step API (and how it can be useful for asynchronous and other complicated test cases).

This is not critical since we already have documentation in api.qunitjs.com for the feature-- just seems like a hugely worthwhile opportunity for a more narrative case study treatment of the feature.

**Comment by trentmwillis** [comment]
Seems like this issue should likely be opened against [qunitjs.com](https://github.com/qunitjs/qunitjs.com) instead.

**Comment by platinumazure** [comment]
Ah crap, you're right. Too used to ESLint where some content in the main
repo gets cross-published to the site on release. I'll close and open on
qunitjs.com.

**Comment by platinumazure** [comment]
Opened here: https://github.com/qunitjs/qunitjs.com/issues/131
