### ISSUE TITLE
Is `done` callback supposed to be fired twice?

### ISSUE THREAD

**Issue by getify** [qunitjs/qunit#1102]
...or am I doing something wrong? From searching and reading issue threads, it seems like this could either be a known bug, a regression, a new bug, or me making a mistake. Sorry my searching failed if this is a dupe.

I'm using v2.1.1. The `done` callback gets fired twice, at the very end, with exactly the same results.

This is how I register it:

```js
QUnit.begin(begin);
QUnit.testDone(testDone);
QUnit.done(done);
```

`begin(..)` is only called once, `testDone(..)` is called once per test, and then `done(..)` is called twice.

**Comment by trentmwillis** [comment]
`done` should normally only be invoked once, _unless_ additional tests/modules get scheduled after `done` has been fired (this usually occurs with asynchronously loaded tests).

**Comment by getify** [comment]
I don't have any asynchronously loaded tests... all tests are created synchronously with: `QUnit.test(..)`.

I should also mention that `done(..)` is only called twice when all tests pass. If I have any failures, `done(..)` only gets called once.

Also, I'm using this in Node v7.1.0.

**Comment by trentmwillis** [comment]
Hmm, only other thing I could think of would be that the processing loop is getting out of whack due to some asynchrony (which is super vague I realize). Any chance you can share a reproduction? Or even stack traces from the two `done` invocations?

**Comment by getify** [comment]
This is my minimal reproduce case (`tests/tmp.js`):

```js
var QUnit = require("qunitjs");

QUnit.config.requireExpects = true;

QUnit.begin(begin);
QUnit.testDone(testDone);
QUnit.done(done);

QUnit.test("a simple test",function t1(assert){
	assert.expect(1);

	assert.ok(true,"one!");
});

QUnit.start();


// ******************************

function begin(details){
	if (details.totalTests > 0) {
		console.log(`Test Suite (${details.totalTests})`);
		console.log("");
	}
	else {
		console.log(`Test Suite: empty!`);
		process.exit(1);
	}
}

function testDone(results){
	if (results.failed > 0) {
		console.log(`Failed: '${results.name}' (${results.failed}/${results.total})`);
		for (let i = 0; i < results.assertions.length; i++) {
			if (results.assertions[i].result === false) {
				console.log(`  ${results.assertions[i].message}`);
			}
		}
	}
	else if (results.passed > 0) {
		console.log(`Passed: '${results.name}' (${results.passed}/${results.total})`);
	}
	else {
		console.log(`No assertions run: '${results.name}'`);
	}
}

function done(results){
	console.log("");

	if (results.failed > 0) {
		console.log(`Failed (${results.failed}/${results.total})`);
		process.exit(1);
	}
	else if (results.passed > 0) {
		console.log(`Passed (${results.passed}/${results.total})`);
	}
	else {
		console.log("No tests run!");
		process.exit(1);
	}
}
```

When I run on the command line:

```
$] node --version
v7.1.0
$] node tests/tmp.js
Test Suite (1)

Passed: 'a simple test' (1/1)

Passed (1/1)

Passed (1/1)
```

You'll see `Passed (1/1)` is being printed twice at the bottom, indicated that `done(..)` was called twice. If I change that test to fail (passing `false` to `assert.ok(..)` for example), it only prints the `Failed` message once, meaning `done(..)` was only called once.

**Comment by trentmwillis** [comment]
Thanks for the reproduction; it was super helpful knowing that this was a setup in Node and not a Browser. I've identified the issue and opened a PR to fix it: https://github.com/qunitjs/qunit/pull/1103
