### ISSUE TITLE
Git builds are out of date

### ISSUE THREAD

**Issue by gibson042** [qunitjs/qunit#1110]
Both http://code.jquery.com/qunit/qunit-git.js and http://code.jquery.com/qunit/qunit-git.css haven't updated since October, despite numerous commits to master since then:
```js
/*!
 * QUnit 2.0.2-pre
 * https://qunitjs.com/
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license
 * https://jquery.org/license
 *
 * Date: 2016-10-31T19:06Z
 */
```

I don't know what uploads them, but it's clearly broken. And for completeness, git builds should also include the commit hash (either in the version like `QUnit 2.0.2-pre+248911105b39d7c5ecb8a788a4942e1128802ff9`, or on a separate line).

**Comment by jzaefferer** [comment]
Looks like Jenkins got stuck 3 months(!) ago: http://jenkins.jquery.com/job/stage.api.qunitjs.com/630/ 

> Started 3 mo 5 days ago; Build has been executing for 3 mo 5 days

Longest build ever??

I'm going to kill this and the other one, maybe that'll help...

**Comment by jzaefferer** [comment]
New QUnit build, should update the git files: http://jenkins.jquery.com/job/QUnit/660/

**Comment by jzaefferer** [comment]
Jenkins job was still using the old repo. Not sure if that was the reason for the failure though. Something about invalid peer dependencies. I've wiped the workspace, maybe a clean npm install will help.

**Comment by jzaefferer** [comment]
Updated! Future commits to master should cause new builds to run immediately: http://jenkins.jquery.com/job/QUnit/
