### ISSUE TITLE
Recursive error in Test#pushFailure and Assert#pushResult

### ISSUE THREAD

**Issue by ryanto** [qunitjs/qunit#1119]
## Tell us about your runtime:

* **QUnit version**: 2.2.1
* **What environment are you running QUnit in? (e.g., browser, Node)**: Browser, Chrome 56
* **How are you running QUnit? (e.g., script, testem, Grunt)**: ember-cli, testem

## What are you trying to do?

Code that reproduces the problem:

Calling this code during an async test after catching an exception.

```js
QUnit.config.current.assert.ok(false);
```

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

The test to fail...

## What actually happened?

Recursive error with call stack exceeded.

`Test#pushFailure` calls `Assert#pushResult`
https://github.com/qunitjs/qunit/blob/master/src/test.js#L388

`Assert#pushResult` calls `Test#pushFailure`
https://github.com/qunitjs/qunit/blob/master/src/assert.js#L107

**Comment by trentmwillis** [comment]
Thanks for the report and investigation! This is a bug, I believe all that we need to do to fix is update [`Test#pushFailure`](https://github.com/qunitjs/qunit/blob/7e5d0556acaff7df2145c394840293f0c3ac8302/src/test.js#L388) to call `Test#pushResult` instead of `Assert#pushResult`.

**Comment by ryanto** [comment]
Cool. I can take a shot at this! I'll put this on tomorrow's TODO list.

**Comment by trentmwillis** [comment]
Fixed by #1120.
