### ISSUE TITLE
Cannot set property 'usedAsync' of undefined with async()

### ISSUE THREAD

**Issue by Happykiller** [qunitjs/qunit#1144]
![2017-04-05 10-15-59](https://cloud.githubusercontent.com/assets/4718138/24696192/ea68c0ba-19e8-11e7-99d1-a8bf36691b7b.png)
* **QUnit version**: 2.3.0
* **What environment are you running QUnit in? (e.g., browser, Node)**:browser
* **How are you running QUnit? (e.g., script, testem, Grunt)**:script,chrome 57.0.2987.133 (64-bit)

## What are you trying to do?

Code that reproduces the problem:

I try to test async function, in minor version all is ok, but i update the version of qunit and now i have an error.

```js
QUnit.module( "Draft" );

QUnit.test( "$.Oda.Test", function() {
    var done = QUnit.assert.async();
    setTimeout(function() {
        QUnit.assert.ok( 1 < 2, "Test" );
        done();
    }, 1500 );
});
```

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

I hope  a pass test :)

## What actually happened?

TypeError: Cannot set property 'usedAsync' of undefined

I put my test file in attachement.

Thx for your support
[test.zip](https://github.com/qunitjs/qunit/files/895534/test.zip)

**Comment by platinumazure** [comment]
Hi @Happykiller, thanks for the issue.

The `QUnit.assert` object actually represents the prototype for assertions in QUnit, so it shouldn't actually be used directly in tests. Instead, we provide an `assert` object as the first argument of the test callback, and you should use that for logging assertions.

Your test should look something like this:

```js
QUnit.module( "Draft" );

QUnit.test( "$.Oda.Test", function( assert ) {
    var done = assert.async();
    setTimeout(function() {
        assert.ok( 1 < 2, "Test" );
        done();
    }, 1500 );
});
```

Give that a try and let me know how it goes!

**Comment by Happykiller** [comment]
I work great thank a lot.
