### ISSUE TITLE
`moduleDone/suiteEnd` not fired for parent module if its tests are already executed

### ISSUE THREAD

**Issue by Arkni** [qunitjs/qunit#1152]
## Tell us about your runtime:

* **QUnit version**: 2.3.0
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node 6.10.0
* **How are you running QUnit? (e.g., script, testem, Grunt)**: Grunt using `grunt-contrib-qunit`

## What are you trying to do?

I want to track the end of every module/test. Basically, I have tests like the following:

```js
QUnit.module('A', function() {
  QUnit.test('a', function(assert) {
    assert.expect(1);
    assert.ok(true);
  });

  QUnit.module('B', function() {
    QUnit.test('b', function(assert) {
      assert.expect(1);
      assert.ok(true);
    });

    QUnit.module('C', function() {
      QUnit.test('c', function(assert) {
        assert.expect(1);
        assert.ok(true);
      });
    });
  });
});
```

And I log them as follow:

```js
grunt.event.on("qunit.moduleStart", function(name) {
  console.log("moduleStart:", name);
});

grunt.event.on("qunit.testStart", function(name) {
  console.log("testStart:", name);
});

grunt.event.on("qunit.testDone", function(name) {
  console.log("testDone:", name);
});

grunt.event.on("qunit.moduleDone", function(name) {
  console.log("moduleDone:", name);
});
```

## What did you expect to happen?

I expected to get the following output:
```
moduleStart: A
testStart: a
testDone: a
moduleStart: A > B
testStart: b
testDone: b
moduleStart: A > B > C
testStart: c
testDone: c
moduleDone: A > B > C
moduleDone: A > B
moduleDone: A
```

## What actually happened?

But instead I got:

```
moduleStart: A
testStart: a
testDone: a
moduleStart: A > B
testStart: b
testDone: b
moduleStart: A > B > C
testStart: c
testDone: c
moduleDone: A > B > C
```

I tracked the issue down to these lines [`src/test.js#L282-L292`](https://github.com/qunitjs/qunit/blob/63bcd15061fc706c9a058ad71c32ada8550ff39e/src/test.js#L282-L292):
```js
if ( module.testsRun === numberOfTests( module ) ) {
	emit( "suiteEnd", module.suiteReport.end( true ) );
	runLoggingCallbacks( "moduleDone", {
		name: module.name,
		tests: module.tests,
		failed: module.stats.bad,
		passed: module.stats.all - module.stats.bad,
		total: module.stats.all,
		runtime: now() - module.stats.started
	} );
}
```

The above code should also check parent modules, otherwise `moduleDone` and `suiteEnd` will be triggered only for the module `C`.

I can provide a PR in case this is not the intended behaviour.

Thanks!

**Comment by Arkni** [comment]
Forgot to mention that if I added a test (e.g. `a2`) after the definition of the module B, I get the following output:
```
moduleStart: A
testStart: a
testDone: a
moduleStart: A > B
testStart: b
testDone: b
moduleStart: A > B > C
testStart: c
testDone: c
moduleDone: A > B > C
testStart: a1
testDone: a2
moduleDone: A
```

**Comment by trentmwillis** [comment]
Definitely a bug, your "expected" behavior is what should happen. A PR with tests would be much appreciated!

**Comment by Arkni** [comment]
@trentmwillis 
Where can I add my tests ? should I extend the file `test/callbacks.js` or create a new one as the `callbacks` file has a its specific logic that I don't want to mess with ?

**Comment by Arkni** [comment]
Never mind. Created a new file.
See #1153
