### ISSUE TITLE
Internal calls to pushFailure (e.g. timeout) result in noisy expected/actual diff reports

### ISSUE THREAD

**Issue by codeworrior** [qunitjs/qunit#1166]
## my runtime:

* **QUnit version**: 2.3.0 ... 2.3.2
* **What environment are you running QUnit in?**: Browsers (Chrome, FF, IE, Edge, phantomjs,...)
* **How are you running QUnit?**: HTML page (either manually or via Selenium or other runners...)

## What are you trying to do?

Run a test that _might_ time out.

```js
QUnit.test("any test", function(assert) {
    assert.async(); // don't call the async done handler -> timeout
    assert.ok(true, "should...");
});
```

## What did you expect to happen?

QUnit HTML reporter just reports "Test timed out"

## What actually happened?

QUnit HTML reporter additionally reports  "expected", "source" and a message that the diff was suppressed (as null is not different from null).

![image](https://cloud.githubusercontent.com/assets/9580095/25223787/b3004e7e-25bc-11e7-913e-f2509121805d.png)

This is quite noisy for a reader and might break tools that evaluate the report (as in our case) or that register for `QUnit.log`.

Most likely, the issue was introduced with [829c41f](https://github.com/qunitjs/qunit/commit/829c41f0e9456302824b249e8673c63ff9d84542#diff-f6c2ded91c9881cdc31b5bfcabb54c3bR394) which contradicts the logic in the HTML reporter at [html.js, lines 764-767](https://github.com/qunitjs/qunit/blob/master/reporter/html.js#L764-L767). The comment for the condition at that location states that `pushFailure`wouldn't provide an `expected`property. This is no longer true due to the mentioned change.

I would suggest to remove the property `expected` again (best compatibility with existing `QUnit.log` listeners, but I didn't check whether this still would allow the reuse of `pushResult`) or give it a special, documented value (would also allow for an expected value of `null`).

**Comment by codeworrior** [comment]
no comments?

**Comment by trentmwillis** [comment]
Sorry for missing this before. I agree that the new behavior is a regression compared to the old behavior. We should restore this to the old behavior (it was just an oversight due to the interaction between the reporter and failure logic).

**Comment by platinumazure** [comment]
The goal of the original commit was to try to refactor and simplify some duplicated code, among other things. So this might need careful examination.

@trentmwillis If someone wanted to compare against `undefined`, would that be a difference of having `expected: undefined` vs expected not being present in the assertion descriptor? If so, I could probably write a PR to add the key more carefully/selectively and fix this. I just want to make sure I understand how it was supposed to work first.
