### ISSUE TITLE
`QUnit.jsDump` was said to be removed in `2.x` but the api docs says otherwise

### ISSUE THREAD

**Issue by Arkni** [qunitjs/qunit#1173]
Although the `2.x` migration guide says that `QUnit.jsDump` should be replaced with `QUnit.dump` which suggests that the object was removed in `2.x` (which is the case), the [`QUnit.dump.parse`](http://api.qunitjs.com/config/QUnit.dump.parse) docs still suggest that it will be removed in `3.0`:
```
NOTE: This method used to be in QUnit.jsDump, which was changed to QUnit.dump.
The old property will be removed in QUnit 3.0.
```

I know that `QUnit.jsDump` was removed in `2.1.1`. It all started by throwing an error in f7da009c646738481ffabda871df3d6195cc7248 and then removing it completely in bdd634d2462573326aa43454fdd3689b347fd072.

I'm just wondering if the removal was on purpose or accidentally. In case of the former, I suggest to omit that notice from api docs. Otherwise, reintroduce it as a bug fix.

By the way, the notice used to say `QUnit 2.0`, and updated to `3.0` in this commit https://github.com/qunitjs/api/commit/5fa1a05db9bce5b2da28ac343dd70c8b99824af8

Thanks!

**Comment by trentmwillis** [comment]
The docs need to be updated. Basically, there was confusion over what we wanted to do with it.

We forgot to remove it in the original 2.x release, so we then updated the messaging to say it will be removed in 3.x. However, after that, we decided that we would just go ahead and remove it, treating it as a bug that it wasn't removed during the original 2.x release.

**Comment by Arkni** [comment]
Thanks for the explanation :)

I opened a PR to remove that note from docs: #1174
