### ISSUE TITLE
Clear require cache on test re-runs

### ISSUE THREAD

**Issue by trentmwillis** [qunitjs/qunit#1182]
When re-running the test suite using `qunit --watch`, the `require.cache` is not cleared. Thus, if any files changed that are required, then those changes won't properly be reflected in the test suite.

**Comment by rwjblue** [comment]
Just ran into this today, glad you are on it. 😄

**Comment by rwjblue** [comment]
FWIW, I am working around this for now by adding the following snippet to one of my test files:

```js
const root = process.cwd();
for (let key in require.cache) {
  if (key.startsWith(root) && !key.startsWith(root + '/node_modules')) {
    delete require.cache[key];
  }
}
```
