### ISSUE TITLE
Memory Leak In QUnit.equiv

### ISSUE THREAD

**Issue by jingxwu** [qunitjs/qunit#1192]
## Tell us about your runtime:

* **QUnit version**: 2.3.2
* **What environment are you running QUnit in? (e.g., browser, Node)**: browser, Chrome Canary
* **How are you running QUnit? (e.g., script, testem, Grunt)**: Grunt. Node.js is on version v5.12.0. We use grunt to launch the test into browser.

## What are you trying to do?

Code that reproduces the problem:

We use QUnit.equiv() to compare objects in our test. The objects can be huge.

```js

```

If you have any relevant configuration information, please include that here:

## What did you expect to happen?
We expect that after QUnit.equiv(a, b) returns, QUnit does not hold reference to a and b, thus allow them to be garbage collected. 

## What actually happened?
We use Chrome dev tool memory tab to take snapshot of the memory, and we found that the global queue "pairs" still holds references to the objects (and their sub-objects) we passed into QUnit.equiv(). When the objects to be compared are big, the leak is big as well. We currently workaround this issue by invoking QUnit.equiv() again with two empty strings, that will replace the global queue with the two empty string, thus free the two big objects.

**Comment by trentmwillis** [comment]
Definitely sounds like a bug, but it doesn't sound like it is too severe since the memory is freed during a subsequent invocation of the function.

Would you mind submitting a PR to fix?

**Comment by jingxwu** [comment]
will do.

**Comment by trentmwillis** [comment]
I have opened #1207 to fix this.
