### ISSUE TITLE
Using native async function as hooks does not work

### ISSUE THREAD

**Issue by sechel** [qunitjs/qunit#1197]
Hi, Im using Qunit 2.3.3 and try to use native `async`/`await` syntax in modern browsers such as Chrome 59 or Firefox 55 to perform some asynchronous work in a `beforeEach` hook. However once I declare the `beforeEach` hook to be an `async `function it simply is not invoked anymore, at least not before any of the tests is. Here is a simple example that illustrates this:
```javascript
let testValue;
QUnit.module('async test module', {
  before: async () => {
    testValue = 42
  }
})
QUnit.test( "check value", function( assert ) {
  assert.ok( testValue == 42, "testValue = " + testValue);
});
```
See this [Fiddle](https://jsfiddle.net/19o4poww/1/).
If you replace this by the Promise returning variant as suggested by the documentation all works well:
```typescript
let testValue;
QUnit.module('async test module', {
  before: () => {
     return new Promise((resolve, reject) => {
      testValue = 42;
      resolve();
    });
  }
});
QUnit.test( "check value", function( assert ) {
  assert.ok( testValue == 42, "testValue = " + testValue);
});
```
I wonder what the difference between both examples is from the perspective of the caller? Is there some qualitative difference between an `async` function that ultimately returns a `Promise` and a function that directly returns a `Promise` without being async itself? 
Thanks for sharing insights.

**Comment by rwjblue** [comment]
This was a fun one to poke at (thank you for making the JSFiddle!). The [case statement](https://github.com/qunitjs/qunit/blob/bbae0a95ee972cd5ca41b871a23f199a74a36b92/src/core/utilities.js#L89-L105) in `objectType` utility needs to be taught about `AsyncFunction`.

```js
let fn = async () => {};
console.log(Object.prototype.toString.call(fn));
// => "[object AsyncFunction]"
```

I assume that we want to make `AsyncFunction` return `function` (though I'm not sure why we don't return `typeof obj` in a `default:` clause there), but others should confirm. Also, I am unsure if we have the ability to target specific tests at specific platforms (e.g. a test that uses untranspiled `async function() {}` would crash Phantom/IE/etc).  If we can, then a test can be added to [this file](https://github.com/qunitjs/qunit/blob/master/test/callbacks.js) that uses an async function and adds a logged callback.

**Comment by trentmwillis** [comment]
We should update that function to properly handle `AsyncFunction`. I think defaulting to `typeof obj` makes sense as well.

We currently have tests that feature detect ([example](https://github.com/qunitjs/qunit/blob/bbae0a95ee972cd5ca41b871a23f199a74a36b92/test/main/deepEqual.js#L159), but I am unsure if that pattern will work for testing this.

**Comment by rwjblue** [comment]
Good news! This issue has been fixed in master by [this change](https://github.com/qunitjs/qunit/commit/a53acdf2a593c9e78d87b4fdaf675117ad366013#diff-f6c2ded91c9881cdc31b5bfcabb54c3bL202). Sadly, I only figured that out after trying in vain to write failing tests 😝 .

**Comment by rwjblue** [comment]
Since I had already written the tests, I went ahead and submitted them as https://github.com/qunitjs/qunit/pull/1198.

**Comment by sechel** [comment]
Thank you, great!
