### ISSUE TITLE
Parsing errors during `qunit --watch`  crash the watcher.

### ISSUE THREAD

**Issue by rwjblue** [qunitjs/qunit#1201]
When running `qunit --watch some-glob/*.js` any errors that occur when the test file is required will crash the watcher process (which must then be restarted manually).

To resolve, [this line](https://github.com/qunitjs/qunit/blob/2.3.3/bin/run.js#L43) would need to be wrapped in a `try`/`catch` block when running with `--watch` (or always?).

**Comment by trentmwillis** [comment]
We should probably just always do it. In the catch, we should add a failing test that lets the user know we couldn't load the file. We should use a test so that it is logged by the reported and the `exitCode` gets properly set at the end of the run.
