### ISSUE TITLE
No try/catch should be respected for returned promises.

### ISSUE THREAD

**Issue by rwjblue** [qunitjs/qunit#1203]
Given:

```js
QUnit.test('does stuff', function(assert) {
  return new Promise((resolve, reject) => {
    setTimeout(reject, 10, new Error('NOOOOOOOO!!!!!');
  });
});
```

When the "no try/catch" option is enabled, we should not install a reject handler on the returned promise (which means the rejection would bubble up naturally).

I propose that we make `Test.prototype.resolvePromise` aware of `config.notrycatch` and avoid adding the reject handler [here](https://github.com/qunitjs/qunit/blob/a3d6cc95660d04f9617fc9248da32bd377338b89/src/test.js#L476-L488).

**Comment by Arkni** [comment]
Looks like this issue is the same as #1149

**Comment by trentmwillis** [comment]
Closing as a duplicate in favor of #1149. I'll try to see where that issue is at soon (and hopefully move it along).

**Comment by rwjblue** [comment]
Sorry about that! I did try to search but missed that one...
