### ISSUE TITLE
Hide skipped tests

### ISSUE THREAD

**Issue by justinbmeyer** [qunitjs/qunit#1208]
I'd like to propose a `hideskipped` tests url parameter that QUnit understands.  We run our tests with saucelabs which has videos of the tests running.  Without being able to hide skipped tests, we are unable to see which test failed.  

<img width="634" alt="cursor_and_sauce_labs___test_details" src="https://user-images.githubusercontent.com/78602/27844750-9307b82c-60eb-11e7-9fef-ad5f037bae66.png">

This would work just like `hidepassed`.  Both should be able to be active at the same time.  

Let me know if this sounds reasonable and I can probably submit a pull request.  Thanks!

**Comment by rwjblue** [comment]
:+1: - This would be very helpful for the various refactoring efforts that we have had in glimmer-vm.

**Comment by rwjblue** [comment]
An alternative here would be to always show failed tests above the rest (not sure if that breaks other constraints though).

**Comment by trentmwillis** [comment]
Sounds reasonable to me. However, if we want to add this option to the UI (as we do with `hidepassed`), then we'll need to do some refactoring as I want to avoid cluttering the UI too much. We'd likely want a multi-select dropdown type feature.

**Comment by gabrielcsapo** [comment]
can we close this issue out as the feature already exists?

**Comment by Krinkle** [comment]
Per <https://github.com/qunitjs/qunit/pull/1315>, I think hiding skipped tests and doing so by default in QUnit has potential to hide problems or make it more difficult to investigate what's going on as they would be missing by default, and thus not be there for new contributors to a code base. I can see that adding friction without much gained value.

The list of tests that have been run or considered to run is imho expected to be complete.

I do note that currently when selecting "Hide passed tests", we leave skipped tests behind and still visible. I'd be open to changing that to consider skipped ones as passing for the purpose of that option. Would that help?

**Comment by rwjblue** [comment]
> I do note that currently when selecting "Hide passed tests", we leave skipped tests behind and still visible. I'd be open to changing that to consider skipped ones as passing for the purpose of that option. Would that help?

Seems like a nice improvement to me...

**Comment by Krinkle** [comment]
I'll circle back to this in a coming weeks, got a few other issues and PRs to handle first but patch welcome in the meanwhile :)
