### ISSUE TITLE
Support CLI --require flag

### ISSUE THREAD

**Issue by tomdale** [qunitjs/qunit#1222]
This is a feature request for the QUnit CLI to support a `--require` flag, similar to mocha's CLI and the `node` binary itself.

The flag itself is pretty simple. It just `require()`s the passed package name before running tests. The flag can be provided multiple times and each package is required in order.

My motivating use case for this is being able to run tests against my code without having to orchestrate a build pipeline.

For example, to use QUnit to test my TypeScript projects, I have to make sure I always transpile both source and tests to JavaScript first before running the CLI. It's easy to forget and end up testing stale code, which can be frustrating. Alternatively I can set up something like testem or Broccoli to orchestrate this for me, but that's a fair bit of complexity when starting a new project and is another tool contributors need to learn in addition to QUnit.

In comparison, with Mocha I can include the `--require ts-node/register` flag and all of my tests and source code get transpiled on demand via a require hook, which is both simple to set up and avoids the problem of testing stale code.

**Comment by trentmwillis** [comment]
This is essentially what I was going to propose in https://github.com/qunitjs/qunit/issues/1221, though a bit smaller in scope. I would like for us also to consider a config file where you can specify these sorts of things, but that can be tracked separately from this specific feature.

PRs welcome!

**Comment by trentmwillis** [comment]
I've opened a PR for this feature: https://github.com/qunitjs/qunit/pull/1271.

**Comment by NullVoxPopuli** [comment]
Does this work? I'm trying ts-node/register. And it appears to freeze my computer
