### ISSUE TITLE
Attributes on qunit-fixture are leaked across tests.

### ISSUE THREAD

**Issue by rwjblue** [qunitjs/qunit#1224]
The `#qunit-fixture` contents are guaranteed to be reset between each test back to its original contents. This helps DOM leaks since any elements added to qunit-fixture during a test run are cleaned up at the end of each test.

However, in some cases attributes are added to `qunit-fixture`. Since [we are only resetting innerHTML](https://github.com/qunitjs/qunit/blob/bac08a415e514649d9ff30b82f5101c7fec739b0/runner/fixture.js#L37) these attributes are never cleared and leak between tests.  This results in cascading failures for Ember (due to helpful assertions that are done by checking for the presence of a given attribute).

The goal of this issue is to confirm that this is something that the maintainers are in favor of fixing, and to determine the best approach.

---

Possible implementations:

1. Change the current system to use `outerHTML` instead of `innerHTML`, remove the existing `#qunit-fixture` and re-add it (in the same location) using the original `outerHTML`.
2. Track the list of attributes before the test, and reset the attributes after the test.

**Comment by rwjblue** [comment]
I personally favor the first option (it seems like it would be the simplest path forward, and would be compatible across our supported browsers)...

**Comment by trentmwillis** [comment]
I consider this a bug. The first approach seems reasonable. The only downside is that you can't reuse the DOM reference between each test, but in general I would consider that a feature to encourage test independence.

**Comment by rwjblue** [comment]
Awesome, thank you for confirming (and suggesting a path forward).

**Comment by rwjblue** [comment]
Submitted #1250 with a fix for this...
