### ISSUE TITLE
`verifySteps(..)` doesn't reset the internal list of steps (and docs are silent on topic!)

### ISSUE THREAD

**Issue by getify** [qunitjs/qunit#1227]
## Tell us about your runtime:

* **QUnit version**: 2.4.0
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node 8.6.0, Chrome 61.
* **How are you running QUnit? (e.g., script, testem, Grunt)**: custom npm script

## What are you trying to do?

I'm trying to use the `step(..)` / `verifySteps(..)` API, but I had a surprise test failure with `verifySteps(..)` called multiple times, interspersed with more `step(..)` calls.

The documentation for this feature doesn't mention what happens in this use-case. So at a minimum, the docs need to be updated. But I also think the current behavior is counter-intuitive.

Code that reproduces the problem:

```js
QUnit.test( "verify steps", function test(assert){
    assert.expect( 5 );

    assert.step( "do stuff 1" );
    assert.step( "do stuff 2" );
    assert.verifySteps( ["do stuff 1","do stuff 2"] );

    assert.step( "do stuff 3" );
    assert.verifySteps( ["do stuff 3"] );
} );

// test fails:
//   expected: [do stuff 3]
//   actual: [do stuff 1,do stuff 2,do stuff 3]
```

## What did you expect to happen?

I assumed that the call to `verifySteps(..)` corresponded to any previous calls to `step(..)` calls, and that once `verifySteps(..)` had been called, all those `step(..)` calls have now been verified, and there's no more reason to check them. Thus, a later call to `verifySteps(..)` would only verify any subsequent calls to `step(..)`. IOW, I expected that the internal list would be reset after each `verifySteps(..)` call.

## What actually happened?

The internal list is not reset, clearly. I can't think of any use-case for why I'd want to call `verifySteps(..)` multiple times, OTHER THAN if I wanted to verify independent groups of steps. I can't imagine any case where I **don't** want the internal list to be reset.

My use-case was that I was indeed expecting the list to be reset, so I could test separate groups of steps. It's quite awkward to have to keep including the whole running list of step values in all subsequent `verifySteps(..)` calls.

As far as I can tell, there's no way to manually reset this internal list to serve my use-case. So an alternative to auto-resetting (which I still think is most intuitive), which would avoid this suggestion being a hard breaking change:

1. Provide a `resetSteps(..)` method so that I could reset after calling `verifySteps(..)`, like calling `verifySteps(..).resetSteps()` together in one statement, ideally.

2. Add an additional boolean parameter (though I generally loathe those) to `verifySteps(..)` that defaults to `false`, but if passed as `true`, does the reset.

**Comment by platinumazure** [comment]
Honestly, this seems like a bug to me. I can't imagine why we would want to keep tracking the internal list for any reason whatsoever. With the current behavior undocumented, I feel like we could release this as semver-patch or semver-minor.

**Comment by trentmwillis** [comment]
I agree that we can treat this as a bug. I don't think I ever thought about potentially calling `verifySteps` more than once in a given test, so we didn't define that behavior.

It makes sense to me, however, that the verification should only be of the steps that occurred since the last verification.

**Comment by trentmwillis** [comment]
This behavior should be fixed by #1233 in the next release. However, going to reopen this as I think we should document this behavior as well (didn't think to do that in the last PR).

**Comment by platinumazure** [comment]
Do we need to fix the docs to explain the new behavior?

**Comment by getify** [comment]
Question: what happens if you've called `step(..)` but never call `verifySteps(..)` -- IOW, leaving that internal queue populated?

**Comment by trentmwillis** [comment]
Each test has a separate internal queue, so it'll just disappear when the test object gets GC'd some time after the test finishes.

**Comment by rwjblue** [comment]
Hmm. I kinda think that should a failure condition, shouldn't it?

**Comment by getify** [comment]
yeah I brought it up because I kinda think it should be a failure. :)

**Comment by platinumazure** [comment]
@getify @rwjblue Could you please open a new issue for discussing whether `assert.step()` without `assert.verifySteps()` should result in a test failure? Thanks!
