### ISSUE TITLE
`assert.async()` + `async function` = gotcha

### ISSUE THREAD

**Issue by getify** [qunitjs/qunit#1229]
## Tell us about your runtime:

* **QUnit version**: 2.4.0
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node 8.6.0, Chrome 61.
* **How are you running QUnit? (e.g., script, testem, Grunt)**: custom npm script

## What are you trying to do?

I'm using `async function` functions for my test functions, but was also (I guess, erroneously) calling `assert.async()` inside them. Turns out this exposes a gotcha. :(

Code that reproduces the problem:

```js
QUnit.test( "test 1", async function test(assert){
    oops();
} );
// Exception: `oops` is not defined

QUnit.test( "test 2", async function test(assert){
    var done = assert.async();
    oops();
    done();
} );
// exception swallowed, test suite aborts silently :(
```

## What did you expect to happen?

I assumed that if an exception was caught as a promise rejection, the `done()` would basically implicitly be called to finish out the test.

## What actually happened?

Strangely, the exception is not only swallowed, but the whole test suite basically silently aborts at that point, so any other defined tests after it don't even seem to run. My guess is that this is because it's no longer running due to the exception, but QUnit is waiting (in vain) for the pending `done()` call to be made, which never will be. :(

It seems like it would make sense for QUnit to, upon receiving a rejected promise from a test function, go ahead and assume that any registered/pending `async()` signals should be completed/canceled/whatever, so the test exception can be reported normally. As a matter of fact, any returned promise that gets resolved, either fulfillment or rejection, should do the same, honestly.

Moreover, the documentation for `assert.async()` could probably be improved by mentioning that there's no reason to call it if you're using an `async function` test function, or you're manually returning a promise/thenable. I didn't know QUnit had that capability built-in, and that function's doc page would have been a great place to mention it to help me avoid this gotcha.

**Comment by trentmwillis** [comment]
Interesting edge case! Definitely a bug. I agree that once a rejection occurs, we should remove remaining locks and move forward with the test suite.

Thanks for a minimal reproduction, will be helpful to get this fixed.

**Comment by rwjblue** [comment]
I haven't looked too deeply here, but I _believe_ that https://github.com/qunitjs/qunit/pull/1241 would address the silent swallowing and aborting.

**Comment by getify** [comment]
@rwjblue I just tried the test from the OP using v2.5.0 (which AFAICT includes the #1241 referenced), and it's still broken.

**Comment by rwjblue** [comment]
Thank you for testing! I’ll try to dig in and see what’s going on when I have a free minute...
