### ISSUE TITLE
Calling `step(..)` but not calling `verifySteps(..)`

### ISSUE THREAD

**Issue by getify** [qunitjs/qunit#1243]
This issue is forked from #1227.

> Question: what happens if you've called step(..) but never call verifySteps(..) -- IOW, leaving that internal queue populated?

The issue is, if you call `assert.step(..)` one or more times within a test case, but for whatever reason don't call `verifySteps(..)`, does that count as an error (test failure)?

I argue it definitely should be. I can't think of any success case where you would have called `step(..)` but not `verifySteps(..)` and that's still OK.

**Comment by platinumazure** [comment]
Thanks @getify. I agree it probably should be a test failure, but we'll see what the rest of @qunitjs/qunit-team thinks.

**Comment by rwjblue** [comment]
I would expect it to be a test failure also. FWIW, I've seen this happen a number of times and every time it has been a bug (returned the wrong promise, didn't follow the correct code path to run `assert.verifySteps`, etc).

**Comment by trentmwillis** [comment]
Seems reasonable to me. Given that a `step` is akin to `assert.ok(true)`, the real value comes from `verifySteps`, so not having it should be treated as a negative signal.
