### ISSUE TITLE
Keyup / Change Event breaks Qunit Test Process

### ISSUE THREAD

**Issue by Nixen85** [qunitjs/qunit#1251]
Hi,
I try to unit test a simple DOM Change which is triggered on $(document).change() and .keyup(). The trigger itself works like a charm.

```
QUnit.test("when input has content login button has svg", function (assert) {

console.log($('.main').find($('input')).length);

$("#user_name3").val("change");
$("#user_name3").trigger("change");
assert.ok($('.main').find($('svg')).length > 0, "btn has arrow as content")
```

When I log something before and after trigger("change"), I can see that the test breaks immediatedly after the change / keyup is triggered, no matter of the statement form:

- `$("#user_name3").trigger("change");`
- `$("#user_name3").change();`
- ` $(document).trigger('change', $('#login--row'));`

etc.

I have now tried numerous ways of expressing the change() call, but nothing worked. if I move the change() call upwards the break happens earlier with it. I get this message from the test runner:

```
Source: | TypeError: Cannot read property 'which' of undefined
-- | --
```
Is this a known issue?

**Comment by trentmwillis** [comment]
I'm skeptical that this is an issue with QUnit itself; looking at the error being thrown:

```
TypeError: Cannot read property 'which' of undefined
```

The most likely culprit appears to be an event handler that is expecting an event to have `which`, but that event isn't properly being passed. Without a failing reproduction to look at, I can't say much more than that.

**Comment by Nixen85** [comment]
Thank you for your hint. I know found that the problem is this if-statement:

if (event.which === 13) {
            $(rootSpan).click();
        }
Probably the missing keyboard event causes the problem and I have to trigger that, too.

**Comment by trentmwillis** [comment]
Glad that helped you track it down. I'm going to close this issue as there doesn't appear to be anything to do on our end.
