### ISSUE TITLE
Add configuration to skip particular test point using test point name

### ISSUE THREAD

**Issue by muthu90ec** [qunitjs/qunit#1259]
Qunit version 2.5.0
Env = browser
just loading it in browser

Running in browser:
chrome v62

## What are you trying to do?
It would be easy to have a qunit configuration that can skip available test points using test point names
For eg:
QUnit.config.testPointsToSkip = ['hello test', 'test point name 2']

QUnit.test( "hello test", function( assert ) {
  assert.ok( 1 == "1", "Passed!" );
});

This will skip hello test.

**Comment by platinumazure** [comment]
I think you might be able to use [`QUnit.config.filter`](http://api.qunitjs.com/config/QUnit.config) to do what you need. `QUnit.config.filter` accepts a regular expression; you could conceivably do something like this:

```js
const testsToSkip = ["hello test"];

QUnit.config.filter = new RegExp(`^(?!${testsToSkip.join("|")}$).*$`);
```

Note that this implementation will fail for strings that use regex special characters, so you would want to be sure to escape regex metacharacters in your own strings before setting `QUnit.config.filter`.

**Comment by trentmwillis** [comment]
Closing this issue as I believe @platinumazure's solution is appropriate. @muthu90ec if you feel we need an additional API for the use case, then feel free to reopen with some explanation.

Thanks for the issue! 🙂
