### ISSUE TITLE
A rejects testcase should be pass, when the rejected and expected value is undefined.

### ISSUE THREAD

**Issue by jsiedentop** [qunitjs/qunit#1268]
Hello,
I found here an unexpected behavior. I think it's a bug. 

I have a test for a function, that should return a promise in rejected state. If the reject call has no value, the testcase fail, although it should be passed.

I wrote a simple example: https://jsfiddle.net/62wxoy6z/9/
```
QUnit.test("test rejects", function(assert) {
  assert.rejects(Promise.reject('test'), 'reject with value passed');
  assert.rejects(Promise.reject(), 'reject without value fail');
});
```

The enviroment doesn't matter, but here is the printout of qunit:
QUnit 2.5.1; Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.102 Safari/537.36 Vivaldi/1.93.955.48

The qunit version is 2.5.1.

I think it's wrong to do only validation if actual is not undefined. 
If actual is undefined and expected is undefined the result should be true. 
If actual is undefined and expected is not undefined the result should be false.
```
function rejects(promise, expected, message) {
	var result = false;
	// ... 
	return then.call(promise, function handleFulfillment() {
		// ...
	}, function handleRejection(actual) {
		if (actual) {
			var expectedType = objectType(expected);

			// We don't want to validate
			if (expected === undefined) {
				result = true;
				expected = null;
			// ... 
		}
		currentTest.assert.pushResult({
			result: result,
			actual: actual,
			expected: expected,
			message: message
		});
		done();
	});
}
```

Thank you!

Jonas

**Comment by trentmwillis** [comment]
Yep, looks like a bug to me. As far as I can tell, we didn't test for this use case. I would expect that when there is no "matcher", any rejection value should count as a "pass".
