### ISSUE TITLE
qunitjs.com ssl cert expired

### ISSUE THREAD

**Issue by tonyfinn** [qunitjs/qunit#1273]
## Tell us about your runtime:

* **QUnit version**: n/a
* **What environment are you running QUnit in? (e.g., browser, Node)**: n/a
* **How are you running QUnit? (e.g., script, testem, Grunt)**: n/a

## What are you trying to do?

Read Qunit docs on https://qunitjs.com/

## What did you expect to happen?

The page would load correctly with a valid SSL cert.

## What actually happened?

> qunitjs.com uses an invalid security certificate. The certificate expired on 2 April 2018, 23:32. The current time is 3 April 2018, 16:15.

**Comment by trentmwillis** [comment]
Thanks for reporting! I'll look into getting the cert updated.

**Comment by trentmwillis** [comment]
Cert has been updated.
