### ISSUE TITLE
Browser autocomplete overlaps qunit module filter autocomplete

### ISSUE THREAD

**Issue by makepanic** [qunitjs/qunit#1276]
## Tell us about your runtime:

* **QUnit version**: 2.5.0
* **What environment are you running QUnit in? (e.g., browser, Node)**: browser
* **How are you running QUnit? (e.g., script, testem, Grunt)**: testem (via ember-cli)

Chromium Version 66.0.3359.139

## What are you trying to do?

Typing in the module filter input triggers the qunit module autocompletion but also the native browser autocomplete. This overlaps and makes filtering a specific module harder as a user has to somehow close the native autocompletion.

![qunit-autocomplete](https://user-images.githubusercontent.com/1205444/39511007-26e6be38-4dec-11e8-8ffe-6b11a367b713.png)

I'm unsure if it's expected behavior but one could possibly disable the browser autocomplete by setting the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete) attribute on the module filter input.

If this is ok, I can open a PR to set the autocomplete attribute to `off`.

Thanks

**Comment by trentmwillis** [comment]
Thanks for the report! I'd consider this a bug and would appreciate a PR turning the browser autocomplete off :+1:
