### ISSUE TITLE
autorun module's tests should belong to autorun module

### ISSUE THREAD

**Issue by krisselden** [qunitjs/qunit#1280]
The autorun test is adding these tests after 5 seconds to whatever module happens to be running in node via QUnit global currentModule, not in autorun due to this change and may not even run at all:

https://github.com/qunitjs/qunit/commit/c8e2ca5c15b592ec0eb51e7d81e80ab95474a255#diff-bc13676ec5de469f49a7f82e44c6c57bR177

These test should be refactored or remove as they are essentially racy at the moment.  Is this actually an important use case to support?

**Comment by trentmwillis** [comment]
This is a known issue. I'm not 100% sure if this is an important use case to support, but refactoring the testing infrastructure to properly support testing it was non-trivial last time I investigated.

**Comment by krisselden** [comment]
If you remove the timeout the test runs in the browser but fails in node.  With the timeout, it is only running in the node side because nothing waits for it and only reason it runs is the browser tests take long enough for it to run.
