### ISSUE TITLE
Chokidar dependency hurts installation ergonomics

### ISSUE THREAD

**Issue by stefanpenner** [qunitjs/qunit#1282]
https://github.com/qunitjs/qunit/blob/master/package.json#L34

Although this dependency is handy (and works well), it introduces a native dependency. Requiring a native dependency can hurt user adoption/ergonomics. Although some are prebuilt, users on newer versions (or odd version) of node, or users who switch node versions, must also deal with a less then ideal user experience.

I would recommend using: http://github.com/amasad/sane/

**Comment by trentmwillis** [comment]
Fixed by https://github.com/qunitjs/qunit/pull/1283
