### ISSUE TITLE
Expired SSL Certificate on https://qunitjs.com/

### ISSUE THREAD

**Issue by cjwillcock** [qunitjs/qunit#1286]
## Tell us about your runtime:

* **QUnit version**: n/a
* **What environment are you running QUnit in? (e.g., browser, Node)**: n/a
* **How are you running QUnit? (e.g., script, testem, Grunt)**: n/a

## What are you trying to do? 
Visit the website at https://qunitjs.com/

## What did you expect to happen?

The page would have a valid SSL certificate.

## What actually happened?

Privacy Error: This server could not prove that it is qunitjs.com; its security certificate expired 2 days ago.

**Comment by trentmwillis** [comment]
Thanks for reporting.

**Comment by platinumazure** [comment]
Pinging @aulvi: I'm told you may have helped resolve this for us in the past. Is this something you can help with this time? And what can be done to help us (or the jQuery/JSF orgs) stay on top of the certificates and renew them before they expire? Thanks!

**Comment by aulvi** [comment]
@platinumazure Hello! Sorry to hear there was an issue w/the certificate. Some time ago we moved to Let's Encrypt but sometimes the certificate doesn't rotate correctly, or the cert is renewed an Nginx doesn't restart and pick it up, etc. We are working to improve monitoring around cert expiration but clearly we're not at 100% capability yet.

In the meantime, I thank you for your patience and encourage you to continue to reach out if you have questions or concerns. Again, I'm sorry for any service interruption.

@cjwillcock Thanks for bringing this to our attention, you rock!

**Comment by trentmwillis** [comment]
Thanks for the context @aulvi! Last time this popped-up it simply resolved itself after a couple days, so hearing this background helps us understand what happened. Let us know if there is a better way to contact you for future issues.

Also, thank you for helping maintain this infrastructure! Much appreciated 😄
