### ISSUE TITLE
Matcher Concept and assertThat

### ISSUE THREAD

**Issue by tobiasso85** [qunitjs/qunit#1309]
Hi,

this is rather a feature request than a bug report therefore i skipped the template.

Would it be possible to implement a matcher concept (like JUnit 4 does with Java).
http://www.vogella.com/tutorials/Hamcrest/article.html
https://github.com/junit-team/junit4/wiki/matchers-and-assertthat

E.g. by implementing a method like
assert.that(obj, matcher)
and providing a set of standard matchers. Custom matchers can then also be created.

**Comment by platinumazure** [comment]
Hi @tobiasso85, thanks for the issue.

If you're asking about how to write custom assertions: We do support [custom assertions](https://qunitjs.com/cookbook/#custom-assertions), which can be made available by augmenting `QUnit.assert`.

If you're aware of the existing custom assertion support and you're asking specifically about matchers: Could you please explain what functionality matchers provide that you can't get with a custom assertion, and why we should add it to core? (Already, it seems that if you wanted matcher functionality, you could implement `assert.that` as a custom assertion, publish that as a QUnit add-on, and then use matchers in your own project. You wouldn't specifically need a change to QUnit core.)

**Comment by Krinkle** [comment]
I'd recommend using a custom assert method for this, from which you call [`assert.pushResult`](https://api.qunitjs.com/assert/pushResult/) to inform QUnit of the result.

This could even be published as a QUnit plugin, which, if anyone does, we can promote on the [plugins directory](https://qunitjs.com/plugins/).

If you encounter any issues or might need a new hook of sorts, feel free to file another issue, or ask in the [chat](https://gitter.im/qunitjs/qunit).
