### ISSUE TITLE
QUnit to fix Lighthouse only two issues; cannot locate target or script.  

### ISSUE THREAD

**Issue by DueTheMath** [qunitjs/qunit#1312]
## Tell us about your runtime:

* **QUnit version**:
* **What environment are you running QUnit in? (e.g., browser, Node)**:
* **How are you running QUnit? (e.g., script, testem, Grunt)**:

## What are you trying to do?

Code that reproduces the problem:

```js

```

If you have any relevant configuration information, please include that here:

**Comment by trentmwillis** [comment]
@DueTheMath did you intend to open this issue? I don't understand the title and the description is merely the default template...

**Comment by trentmwillis** [comment]
I'm going to close this. Feel free to reopen if you meant to open and can provide more details.

**Comment by DueTheMath** [comment]
I keep trying to work on all these issues too myself.  i am not sure what
closed means or why i keep getting these emails but then again probably
neither are you.  so QUnitsto/Qunits a good thing thanks, carolyn
