### ISSUE TITLE
qunit:all test hanging

### ISSUE THREAD

**Issue by brettz9** [qunitjs/qunit#1313]
## Tell us about your runtime:

* **QUnit version**: `master` (2.6.3-pre)
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node
* **How are you running QUnit? (e.g., script, testem, Grunt)**: Grunt

Node 9.2.1

## What are you trying to do?

Code that reproduces the problem:

```
npm test
```

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

The tests to pass (or fail)

## What actually happened?

The tests just hanged at the first test

> Running "qunit:all" (qunit) task
> Testing http://localhost:8000/test/sandboxed-iframe.html

Any idea what I may be missing? I'm on a Mac...

**Comment by DueTheMath** [comment]
this is only a notebook and only information too; perhaps considering QUnit.js a friendly envioronment did you think of that   Js means something is missing and it should might as well not be....thats Mac for ya.

**Comment by platinumazure** [comment]
Can you include your Grunt config please? Thanks!

**Comment by DueTheMath** [comment]
I did not choose Grunt and it is because I don't use a Macbook.  Only Chromebooks are Notebooks.  Computers like Macs front that they are because they have dual OSX systems you know; HP was the first to come out with their own idea of a Notebook for like Five Hundred Dollars and regretted it it was only slow and not built heavy equipt for your thinking.  words these days....lol

**Comment by DueTheMath** [comment]
Grunt's WebSite is https://gruntjs.com/

**Comment by brettz9** [comment]
@platinumazure : Hi, I reported the issue. I was just running `npm test` in `master` while trying to develop in QUnit....

**Comment by DueTheMath** [comment]
developing in Master while using Xtreme Bios does work better on Windows.   Npm tests are not standard and you can never let a Mac be left alone!  That's news for you.  QUnit is new too but Developing these days OMYGOD.!

**Comment by DueTheMath** [comment]
Whoever you are platinumazure keep your comments to yourself about asking people for their advice then insulting them on their form Comments Page.  as a matter of fact who do you think you are.

**Comment by DueTheMath** [comment]
@DueTheMath I apologize, I should have been more clear.

Under what circumstances are you running npm test? Is this while trying to develop in QUnit, or in some other repository? You say you are just running npm test and then some Grunt task qunit:all is running, but I don't have any more information than that. Until you give me some more context, I can't help you. I really want to help, so please give me some more context if you can. Thanks!

**Comment by DueTheMath** [comment]
> @DueTheMath Are you @brettz9? Can you speak for his/her configuration? I'm a bit confused why you are even commenting here.

**Comment by DueTheMath** [comment]
> @DueTheMath Are you @brettz9? Can you speak for his/her configuration? I'm a bit confused why you are even commenting here.

you need to leave me alone

**Comment by platinumazure** [comment]
Hi @brettz9, thanks for clarifying! Apologies for the confusion on my end.

I can't reproduce, though I'm running on Windows. I'll try to dig into the code later this weekend to try to get an idea of what might be going on.

If you haven't just done a fresh install, maybe it would be worth deleting node_modules and rerunning npm install, to ensure you have the latest and greatest dependencies?

**Comment by platinumazure** [comment]
@DueTheMath Apologies, I made a few edits to one of my posts because I was confused. Definitely not trying to harass you. On the other hand, you've made a number of irrelevant comments in this thread. Please stop doing that. I'll happily leave you alone.

**Comment by brettz9** [comment]
Using yarn instead this time (and removing `node_modules` as you said) did the trick, thanks!
