### ISSUE TITLE
QUnit 2.7 claims compatibility with Node 4, but fails

### ISSUE THREAD

**Issue by Turbo87** [qunitjs/qunit#1321]
Some of our CI systems are still running on Node 4 and the `qunit` npm package claims that it's still compatible with it:

https://github.com/qunitjs/qunit/blob/2.7.0/package.json#L100

Unfortunately `qunit` has a dependency on `sane@4` though, which is Node 6+. It seems that this dependency bump was introduced without a change to the Node requirements of QUnit 🤔 

As our CI will try to install the latest `qunit`, it will try to install `sane@4` now and fail:
```
error sane@4.0.1: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "4.9.1"
```

/cc @trentmwillis @stefanpenner

**Comment by rwjblue** [comment]
This was discussed in https://github.com/qunitjs/qunit/pull/1299, and QUnits policy roughly matches Ember CLI’s (only supporting supported node versions). The engines field should have been updated in that PR though...

**Comment by Turbo87** [comment]
Hmpf, that is quite unfortunate... Do we need to pin it then in ember-cli-qunit?

**Comment by rwjblue** [comment]
We should pin in ember-qunit (IIRC ember-cli-qunit doesn’t have a qunit for directly any more), then release a major I guess (need to drop Node 4 and ember-cli < 2.13 over there).

**Comment by Turbo87** [comment]
@rwjblue yep, that seems like the right thing to do to me. see https://github.com/emberjs/ember-qunit/pull/353

**Comment by trentmwillis** [comment]
Oops, closed prematurely. Need to update the `engines` field in `package.json`: https://github.com/qunitjs/qunit/blob/ed8807438670b34763bd422be77525c857e6dabd/package.json#L100
