### ISSUE TITLE
Add async support for QUnit.on() callback

### ISSUE THREAD

**Issue by step2yeung** [qunitjs/qunit#1329]
Add the same async promise support in other QUnit callbacks (eg: begin, done, moduleStart, etc..) to QUnit.on() as discussed here: https://github.com/qunitjs/qunit/pull/1307

**Comment by step2yeung** [comment]
Possibly as part of this enhancement, address the drop of code coverage due to adding of polyfills.

**Comment by Krinkle** [comment]
@step2yeung What is the use case for having QUnit hold back test execution for an event handler? I would expect a reporter and other event handlers to not mutate the shared state.

Instead of making QUnit wait for async resolution, I would be actually be interested in exploring (very early idea right now) a possible extreme opposite. That is, to trigger these events in an asynchronous way so that they cannot even synchronously mutate or block test execution (e.g. fire from setTimeout/Immediate/nextTick).

In order to make sure that reporters can still report progress when the test suite only has synchronous tests, we'd make sure that within QUnit itself we breath a tick every once in a while. (I don't recall whether we do this already.)

**Comment by step2yeung** [comment]
The feature that I am implementing in ember exam to dynamically load balance tests between a number of browsers running test with QUnit. A test server receives events and responds with the next test to execute in real time with the browser using events. The goal being long running tests won't cause other tests to wait, but can be distributed to other free browsers.

We use promises handling in QUnit callbacks implemented with #1307 to handle the events communication.
Another possible usecase is to use Chrome DevTools Protocol to communicate with the browser to understand browser usage (memory, or run profiler) between tests.

@Krinkle I'm curious on your use case in not allowing pauses in test execution.

**Comment by Krinkle** [comment]
That's a great use case, no problem. It is not about whether I allow a test to be paused. It is about optimising the API for easy-of-use toward end-users and plugin developers, and to reduce long-term cost of maintainer's spare time. As such, I don't want to support multiple ways of achieving the same end-result if the effort required for end-users is not significantly improved.

QUnit allows a test sequence to expand (it does not need everything to be registered up front). As such, you can continue to call `QUnit.module()` and `QUnit.test` even after a test has started executing.

Have you considered using this as the way to drive your test, and thus control execution of tests that way? In general I think of QUnit as library, not as a framework. I don't want to limit what you can do, or encourage that it needs to be driven from within. Rather, I want to make sure see if this can already be done through existing primitives. I think "event emitters" should be one-way channels whenever possible, and not allow changing of behaviour. This makes the system easier to understand, and I think generally encourages patterns that result in a speedier and more stable outcome.

If the above doesn't work though, I'd gladly reconsider. I have no principle objection to it.

**Comment by Krinkle** [comment]
The "on()" events are for reporting purposes, and comply with the js-reporters spec, which is synchronous. I don't think we should break that independence by making them support something non-standard.

However note that QUnit also has its own methods for these events, which in the latest version do support promises and async functions. E.g. the equivalent of `QUnit.on("suiteStart", fn)` is `QUnit.moduleStart(fn)`. Feel free to ping here or file a new issue if you encounter issues with that.

See also my suggestion about overloading QUnit.test(), and related to the Ember use case: https://github.com/qunitjs/qunit/issues/1228.
