### ISSUE TITLE
Hide content in htmlreporter UI

### ISSUE THREAD

**Issue by gabrielcsapo** [qunitjs/qunit#1330]
# Question

Would it be possible to change the htmlreporter UI to show something like

| test output | current tests| 

where test output is a queue and the current tests area is a static area where just the tests render into? 

# Reasoning

The experience right now is very jarring as tests progress or fail, the UI is shifting content around.

**Comment by Krinkle** [comment]
Can you include an example or screenshot to show which content you are referring to? Is this content created by your tests, or the QUnit test results/progress UI?

If this is about content fixtures created by your tests, are you using `#qunit-fixture`?

This element has built-in styles that visually hide the content when running tests.
