### ISSUE TITLE
Reduce size of module dependency graph

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1342]
The qunit npm package has quite a lot of dependencies installed when used in another project.

The total number of packages installed according to (as of QUnit 2.8.0) is **143 packages**.  (Not including dev dependencies, that are only installed for QUnit contributors.)

* Graph visualisation: <https://npm.anvaka.com/#/view/2d/qunit/2.8.0>
* Tree visualisation: <https://snyk.io/test/npm/qunit/2.8.0?tab=dependencies>

Assuming we won't be investing in a way to sandbox QUnit, I believe this is beyond what we can reasonably expect a developer to audit before installing. Keeping in mind that merely running `npm install` in a Git project using qunit, is enough for any of these packages turned bad to start scraping `process.env`, `~/.ssh`, etc (e.g. through postinstall hooks, or at run-time).

I'm aiming with this task to take a serious look at what abstractions we need and are providing value, and which we might be better off not using a package for. For problems where the abstractions can be "simple enough to obviously have no problems", it might be better to simply inline it within our repo (with proper licensing information inline, if based on an existing package). In such case, I believe the theoretical value gained from future updates is non-existent or small enough to not outweigh the loss in understandability and security of QUnit overall. If in these areas we do find a rare bug one day, we can easily update it by hand.

Goal: Maximum 20, preferably less than 10.

QUnit prides simplicity, I believe. We've done well to uphold that in our API. I'm hoping we can reach simplicity in our dependency graph as well!

Relating reading:
* <https://jakearchibald.com/2018/when-packages-go-bad/>
* <https://24ways.org/2018/its-beginning-to-look-a-lot-like-xssmas/>
* <https://css-tricks.com/how-to-worry-about-npm-package-weight/>
* <https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream>

**Comment by trentmwillis** [comment]
I'm on board with this!

**Comment by Krinkle** [comment]
```
$ npm install --prod   
...
added 9 packages from 6 contributors in 3.517s
found 0 vulnerabilities

$ npm ls
qunit@2.8.1-pre
+-- commander@2.12.2
+-- js-reporters@1.2.1
+-- minimatch@3.0.4
| `-- brace-expansion@1.1.11
|   +-- balanced-match@1.0.0
|   `-- concat-map@0.0.1
+-- node-watch@0.5.9
`-- resolve@1.5.0
  `-- path-parse@1.0.6
```

qunit now has 9 dependencies exactly, for a total of 10 packages for downstream users.

**Comment by Krinkle** [comment]
QUnit now has 9 dependencies exactly, for a total of 10 packages for downstream users.

```
$ npm install --prod   
...
added 9 packages
found 0 vulnerabilities

$ npm ls
qunit@2.8.1-pre
+-- commander@2.12.2
+-- js-reporters@1.2.1
+-- minimatch@3.0.4
| `-- brace-expansion@1.1.11
|   +-- balanced-match@1.0.0
|   `-- concat-map@0.0.1
+-- node-watch@0.5.9
`-- resolve@1.5.0
  `-- path-parse@1.0.6
```

> Before:
> _QUnit 2.8.0 has 142 dependencies. – <https://snyk.io/test/npm/qunit/2.8.0?tab=dependencies>_
