### ISSUE TITLE
Require Windows tests passing on pull requests

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1347]
To avoid https://github.com/qunitjs/qunit/pull/1346 in the future, and to embrace Windows support, perhaps we should integrate AppVeyor for pull requests and require it to be passing like we do for Linux (on Travis CI).

Alternatively, we could look into adding Windows to the Travis CI build matrix, which has experimental support as of <https://blog.travis-ci.com/2018-10-11-windows-early-release>.

Thoughts?

/cc @platinumazure @trentmwillis

**Comment by platinumazure** [comment]
ESLint uses AppVeyor for this very purpose and it works pretty well for us.

One small drawback (although I'm not sure if this is still the case) is that AppVeyor runs builds in series, so the more Node versions we test there, the longer the build will take. ESLint chose to only run latest supported Node versions on AppVeyor (but all supported versions on Travis) to trade off between coverage and PR status check speed. Probably not a decision we need to make now, but wanted to make you aware.

**Comment by trentmwillis** [comment]
I think we had it enabled at one point...I'm in favor in general.

One other thing to note though: AppVeyor (last I checked) did not have support for organizations, so the account is currently setup under @leobalter's personal account. We should see if that has changed. If it hasn't, then I think it would be worthwhile to look into using the new Travis Windows CI.

**Comment by Krinkle** [comment]
@trentmwillis Aye, good point.

I'm looking at it now and thought maybe this was resolved as part of the shift from "Integrations & services" (deprecated) to "GitHub Apps". The new way to enable AppVeyor, is via <https://github.com/organizations/qunitjs/settings/installations> (e.g. no personal tokens or hooks). Once enabled as a GitHub app, AppVeyor is automatically sent events from GitHub.

But.. it seems they still ignore them by default and require a person to login at <https://ci.appveyor.com/> to "add" it under their name. So it's now under both @leobalter and myself.... <https://ci.appveyor.com/project/Krinkle/qunit>.

**Comment by Krinkle** [comment]
I'm trying out Travis' Windows image in my fork, and running into an "Chrome DLL error". This appears to be specific to Windows Server 2016 and the (older) Chrome version that grunt-contrib-qunit ships via its pinned version of puppeteer.

At AppVeyor we currently use "Windows Server 2012", which appears unaffected. Upgrading to Chrome 72 or later resolved the issue. Pul request pending at https://github.com/gruntjs/grunt-contrib-qunit/pull/155.
