### ISSUE TITLE
Require npmjs.org 2FA for package publishing

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1348]
Reading through [RELEASE.md](https://github.com/qunitjs/qunit/blob/2.8.0/RELEASE.md) (Thanks @trentmwillis for writing this!), it noticed it says one has to temporarily disable the npmjs.org account protection from "Authorization  and publishing" to "Authorization only".

See <https://docs.npmjs.com/requiring-2fa-for-package-publishing-and-settings-modification>

This issue is to:
* Determine which parts of the release process would need to change to avoid this step,
* How we could improve them, and whether to do so,
* (If we agree) Make the necessary changes,
* (If we agree) Enable the "Require 2FA to publish" option at <https://www.npmjs.com/package/qunit/access>.

**Comment by platinumazure** [comment]
ESLint recently implemented 2FA for npm publishes- I'll keep an eye out here for questions where that experience could be useful.

**Comment by Krinkle** [comment]
I've enabled the option in question a while back as general security measure (and we've been briefly turning it off around releases). I'll work on a simpler (but less automated) release process as part of https://github.com/qunitjs/qunit/issues/1350.
