### ISSUE TITLE
Document best practices for assert.expect()

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunit#1354]
Based on the discussion in jquery/qunit#666, there are some anti-patterns around `assert.expect`. We should document how to use it properly, along with the anti-patterns to avoid.

Assigning this to @JamesMGreene since he had some examples for that. Along with updating http://api.qunitjs.com/expect/ we can also check other pages, like the cookbook.

**Comment by Krinkle** [comment]
Done at https://api.qunitjs.com/assert/expect/

> This is most commonly used as `assert.expect(0)`, which indicates that a test may pass without making any assertions. This means the test is only used to verify that the code runs to completion, without any uncaught errors. This is is essentially the inverse of [assert.throws()](https://api.qunitjs.com/assert/throws/).
>
> This can also be used to explicitly require a certain number of assertions to be recorded in a given test. If afterwards the number of assertions does not match the expected count, the test will fail.
>
> It is recommended to test asynchronous code with [assert.step()](https://api.qunitjs.com/assert/step/) or [assert.async()](https://api.qunitjs.com/assert/async/) instead.

See also https://github.com/platinumazure/eslint-plugin-qunit/issues/382
