### ISSUE TITLE
Arrow functions as test/module hook callbacks

### ISSUE THREAD

**Issue by platinumazure** [qunitjs/qunit#1357]
The API documentation for QUnit.module mentions that tests are run with a test environment set as `this` within the test. If people are to take advantage of this functionality, they need to remember to use function expressions or function declaration references; if they don't, the mechanics of arrow functions implies that the outer `this` context is used.

Is this worth noting somewhere? Would a PR be accepted for adding such a note?

**Comment by Krinkle** [comment]
I agree with @trentmwillis but I also think the docs could have been better. I've re-written the docs for `QUnit.module` in commit https://github.com/qunitjs/qunit/commit/6894a957941099059470f5238c45299a29a and I think this is clearer now: <https://api.qunitjs.com/QUnit/module/>
