### ISSUE TITLE
Make CLI tests passing on Windows

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1359]
As part of https://github.com/qunitjs/qunit/issues/1347 I tried to consolidate the main tests and CLI tests under plainly `npm test`, but ran into the problem that the CLI tests don't currently pass on Windows.

For a while I tried to make them work, thinking it was an issue with Travis (because AppVeyor is green). Only to realise they would also fail on AppVeyor. It's just that we don't run them there. 

So.. filing this as a separate issue to resolve later.

I ran into two issues:

1. Running an executable from a sub directory doesn't work.

The `bin/qunit test/cli/*.js` part of `grunt && bin/qunit test/cli/*.js` isn't working on Windows. It fails as follows:

```
'bin' is not recognized as an internal or external command, operable program or batch file.
```

This is presumably due to the use of a forward-slash. Some sources on the internet suggested that wrapping them in quotes and/or using `./` would make it work, but that didn't seem to do the trick.

What did work is changing the invocation to `node bin/qunit test/cli/*.js`.

2. The child processes created by the CLI tests fail.

```
  expected: undefined
  stack: Error: Command failed: C:\windows\system32\cmd.exe /s /c "../../../bin/qunit --reporter npm-reporter"
'..' is not recognized as an internal or external command,
operable program or batch file.
    at Promise.all.then.arr (C:\projects\qunit\node_modules\execa\index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  ...
```

This is presumably the same issue in essence. `../../../` doesn't work in that way on Windows. This might be an easy fix given that we invoke it from within Node.js, so we could easily vary the logic by `process.platform` and/or utilise something like `path.join()` to get the slashes right.

**Comment by trentmwillis** [comment]
Thanks for working on this!

**Comment by XhmikosR** [comment]
For what is worth, the problem is that Windows doesn't support shebangs. Which means `bin/qunit test/cli/*.js` is wrong. It should be `node bin/qunit test/cli/*.js`

**Comment by Krinkle** [comment]
Thanks, that makes a lot of sense!

**Comment by Krinkle** [comment]
I've made these two changes and it's getting somewhere, although still some test failures.

Draft commit: https://github.com/qunitjs/qunit/commit/a04fb8efd906c45764f7fea1136337425ea1de96

>  [WIP] Re-enable CLI test on Windows
> 
> * For subprocesses in the CLI tests, use `process.execPath` to
>   use the same node program for subprocesses regardless of its
>   name, extension or location (e.g. 'nodejs' or 'node.exe' etc.)
> 
> * Use 'node bin/qunit.js' instead of 'bin/qunit.js' because
>   the hashbang (`#!/usr/bin/env`) atop the executable is not
>   supported on Windows.

<https://travis-ci.com/github/qunitjs/qunit/builds/177733756>

The first one is:

```
ok 1 find-reporter > correctly finds js-reporters reporter by name
ok 2 find-reporter > correctly finds npm package reporter by name
ok 3 CLI Reporter > runs tests using the specified reporter
ok 4 CLI Reporter > exits early and lists available reporters if reporter is not found
ok 5 CLI Reporter > exits early and lists available reporters if reporter option is used with no value
ok 6 CLI Main > defaults to running tests in 'test' directory
ok 7 CLI Main > errors if no test files are found to run
not ok 8 CLI Main > accepts globs for test files to run
  ---

  message: "Promise rejected during "accepts globs for test files to run": Command failed: C:\Windows\system32\cmd.exe /s /c "C:\ProgramData\nvs\node\14.7.0\x64\node.exe ../../../bin/qunit.js 'glob/**/*-test.js'"
No files were found matching: 'glob/**/*-test.js'
"
  severity: failed
  stack: Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\ProgramData\nvs\node\14.7.0\x64\node.exe ../../../bin/qunit.js 'glob/**/*-test.js'"

No files were found matching: 'glob/**/*-test.js'
```
