### ISSUE TITLE
Semaphore imbalance when returned promise resolves when test timed out.

### ISSUE THREAD

**Issue by rwjblue** [qunitjs/qunit#1375]
## Tell us about your runtime:

* **QUnit version**:2.9.1
* **What environment are you running QUnit in? (e.g., browser, Node)**: Browser & Node
* **How are you running QUnit? (e.g., script, testem, Grunt)**: `qunit` Node CLI / `testem`

## What are you trying to do?

A test returning a promise (or an `async`) that runs longer than the allowed timeout period, causes an internal test semaphore imbalance if the returned promise ever settles.

Code that reproduces the problem:

```js
QUnit.module('group of tests', function(hooks) {
  QUnit.test('one', function(assert) {
	assert.timeout(10);

    return new Promise(resolve => setTimeout(resolve, 20));
  });

  QUnit.test('two', function(assert) {
   	return new Promise(resolve => setTimeout(resolve, 20))
      .then(() => {
        assert.ok(true, 'all is well');
      });
  });
});
```

[CodePen Demo Here](https://codepen.io/rwjblue/pen/GzLqXa)

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

Test `one` should fail (due to timeout), and test `two` should pass.

## What actually happened?

Test `one` fails properly (due to timeout), however test `two` _also_ fails with the following message:

```
Tried to restart test while already started (test's semaphore was 0 already)
```

**Comment by rwjblue** [comment]
I did some debugging with @scalvert for this issue on Friday and we believe we have a good understanding of what is going on and how to fix it (so hopefully we'll have a PR inbound soon), but I wanted to create the issue for discussion also.

---

The basic issue is that `Test.prototype.resolvePromise` here always calls `resume` (in both reject and fulfilled scenarios) which attempts to decrements the individual tests semaphore:

https://github.com/qunitjs/qunit/blob/766db374a0215d8b4b56cc80be27d2d9d218f80d/src/test.js#L523-L539

After a test timeout ([see this for what that does](https://github.com/qunitjs/qunit/blob/766db374a0215d8b4b56cc80be27d2d9d218f80d/src/test.js#L747-L751)) we reset the tests semaphore to `0`, but we don't also prevent `resume` from running when the promise finally _does_ resolve.

When the promise finally resolves, the test is "long gone" but `resume` is still called which decrements the tests semaphore (now to `-1`) and calls `internalStart`. When `internalStart` is called and the passed in `test.semaphore < 0` we call `pushFailure` to log the semaphore imbalance.

Unfortunately, since `pushFailure` _always_ logs failures to the `QUnit.config.current` test (or creates a new global failure) this `pushFailure` about semaphore imbalance causes a completely unrelated test to fail (the test that _happens_ to be running) **not** the test that actually had the imbalance.

**Comment by trentmwillis** [comment]
Thanks y'all for the detailed report and PR to fix. I'll cut a new release tomorrow.
