### ISSUE TITLE
CLI should not exit with process.exit

### ISSUE THREAD

**Issue by krisselden** [qunitjs/qunit#1383]
## Tell us about your runtime:

* **QUnit version**: latest
* **What environment are you running QUnit in? (e.g., browser, Node)**: node
* **How are you running QUnit? (e.g., script, testem, Grunt)**: qunit node cli

## What are you trying to do?

Code that reproduces the problem:

Test leaks timeout that would normally prevent node from exiting.

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

QUnit shouldn't force exit.

## What actually happened?

QUnit forces exit, hiding leaks.

**Comment by rwjblue** [comment]
@krisselden mind whipping up a demo repo that shows the bug?

**Comment by Krinkle** [comment]
🤖  _Closing stale issue. If this is still an issue, feel free to mention me here, or create a new issue, or [Chat with us](https://gitter.im/qunitjs/qunit)._
