### ISSUE TITLE
Tests involving window scrolling fails in iOS due to iframe not being scrollable

### ISSUE THREAD

**Issue by pudupa** [qunitjs/qunit#1386]
## Tell us about your runtime:

* **QUnit version**:
* **What environment are you running QUnit in? (e.g., browser, Node)**:
* **How are you running QUnit? (e.g., script, testem, Grunt)**:

## What are you trying to do?

Code that reproduces the problem:

```js

```

If you have any relevant configuration information, please include that here:

**Comment by trentmwillis** [comment]
Without further information and some more specific instructions on how to reproduce, there's not much we can do here.
