### ISSUE TITLE
assert.throws fails when expected is an arrow function: 'prototype' property of expected is not an object

### ISSUE THREAD

**Issue by ohze** [qunitjs/qunit#1389]
## Tell us about your runtime:

* **QUnit version**: 2.9.2 & 2.9.3-pre
* **What environment are you running QUnit in? (e.g., browser, Node)**: browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0
* **How are you running QUnit? (e.g., script, testem, Grunt)**: script

## What are you trying to do?

Code that reproduces the problem:

[run in jsbin](https://jsbin.com/dafijuqepi/edit?html,js,output)
```js
function f() {
  throw new Error('err');
}
function errCheck(e) {
  return e.message == 'err';
}
QUnit.test('foo', (t) => {
  t.throws(f, errCheck); // this assert is passed
  t.throws(f, (e) => e.message == 'err'); // this assert fails
})
```

## What did you expect to happen?
test passed

## What actually happened?
1st assert passed,
but 2nd assert fails:
```
'prototype' property of expected is not an object
```

**Comment by ohze** [comment]
can be fixed by changing [assert.js#L298](https://github.com/qunitjs/qunit/blob/08f1c69/src/assert.js#L298)
```js
} else if ( expectedType === "function" && actual instanceof expected ) {
```
to:
```js
} else if ( expectedType === "function" &&
            expected.prototype !== undefined && actual instanceof expected ) {
```

**Comment by trentmwillis** [comment]
Since you have identified the fix already, would you mind opening a Pull Request to fix it?
