### ISSUE TITLE
Provide a way to reset the test server

### ISSUE THREAD

**Issue by sduquej** [qunitjs/qunit#1390]
## Tell us about your runtime:

* **QUnit version**: 2.6
* **What environment are you running QUnit in? (e.g., browser, Node)**: browser
* **How are you running QUnit? (e.g., script, testem, Grunt)**: testem, via `ember test`

## What are you trying to do?

We have a large test suite that we don't expect to run entirely in a single browser as it'd take ages to complete (and maybe even crash before it's finished). By default QUnit loads all tests and starts to run them, interacting with the dropdown to filter specific modules can get tricky as tests run in the background. 

We've worked around this by adding a default filter that doesn't match any tests as the runner is started. This gets us to a state of "all tests are loaded and nothing is running or filtered to run". 

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

The abort button gets us the first part of this state but I haven't been able to find a way to get the latter part (nothing is filtered to run). 

## What actually happened?
I've added a button to our test page that changes the URL as a workaround but this seemed like something that could be widely useful for others if there was first-class support.

**Comment by trentmwillis** [comment]
Can you try upgrading to version 2.7 or later? https://github.com/qunitjs/qunit/pull/1311 landed in 2.7 and should help with some of the memory load if using `hidepassed`.

Alternatively, you could try breaking up your test suite and using something like https://github.com/JamesMGreene/qunit-composite

**Comment by Krinkle** [comment]
🤖  _Closing stale issue. If this is still an issue, feel free to mention me here, or create a new issue, or [Chat with us](https://gitter.im/qunitjs/qunit)._
