### ISSUE TITLE
Add support for Google Apps Script

### ISSUE THREAD

**Issue by ahochsteger** [qunitjs/qunit#1392]
It would be great, if QUnit could be used as testing framework for Google Apps Scripts.

Here is an experimental fork of QUnit that already does this (and works for me):
https://github.com/simula-innovation/qunit/tree/gas/gas
The problem with this fork is that it is not maintained for several years and missing new features of QUnit.

Here is some information about how development with Google Apps Script is working:
https://developers.google.com/apps-script/guides/projects
https://developers.google.com/apps-script/guides/clasp

**Comment by trentmwillis** [comment]
Can you explain which changes need to made in QUnit to support Google Apps Script?

**Comment by ahochsteger** [comment]
I guess this comparison shows the changes that were done for the old fork of qunit:
<https://github.com/qunitjs/qunit/compare/master...simula-innovation:gas>

**Comment by trentmwillis** [comment]
That diff has a lot of changes without much context as to what the changes are fixing/enabling. Having specific action items is needed if we want to move this forward.

Asking to support GAS without specifying how QUnit does not currently support it means that we're very unlikely to fulfill the request.

**Comment by ahochsteger** [comment]
Since I've found a better way for me to test my GAS scripts I'm not depending on the GAS-integration for QUnit anymore.
Feel free to close the issue.

**Comment by barretodavid** [comment]
@ahochsteger would you mind sharing what are you using to unit test your GAS scripts?
