### ISSUE TITLE
Consider renaming "Main assertions" page

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1396]
Almost every time I navigate to <https://api.qunitjs.com/> I find myself clicking "Main assertions" when looking up one of the assert methods, like `propEqual` or some such.

Then after a brief moment of confusing and a failed attempt at expanding the page further, I realise I should have clicked "Assertions" instead.

I don't have any good ideas off the top of my head, but we may want to consider renaming this page.

**Comment by trentmwillis** [comment]
Currently, on the left-hand nav we group them under "Main Methods". That seems reasonable for now. At the least, they shouldn't say "Assertions".
