### ISSUE TITLE
Add QUnit.test.only as alias for QUnit.only (and QUnit.test.todo, QUnit.test.skip)

### ISSUE THREAD

**Issue by ryanto** [qunitjs/qunit#1402]
Hello!

I'm wondering if it would be a good idea to chain module methods together to describe each test. Here's what I'm thinking.

Instead of...

```js
import { module, test, only } from 'qunit';

module('something', function() {
  test('first', function() {
    // the first test
  })

  only('the test im working on', function() {
    // the second test
  })
})
```

We could allow the following syntax...

```js
import { module, test } from 'qunit';

module('something', function() {
  test('first', function() {
    // the first test
  })

  test.only('the test im working on', function() {
    // the second test
  })
})
```

The main reasoning behind this change is as tests files grow in size I don't have to manage the imports. As I toggle `only` on and off I have to add and remove the import, which gets cumbersome. Chaining only off of test would avoid this.

This is a half baked thought, but I figured I'd start some discussion around this.

**Comment by Arkni** [comment]
I was intending to work on this after adding `only`, `skip` and `todo` to modules (See #1163), as @trentmwillis suggested in https://github.com/qunitjs/qunit/issues/1163#issuecomment-294503758, but got busy and eventually the issue was lost in time.

**Comment by ryanto** [comment]
Very cool! Thanks for adding it to `module` @Arkni 

@trentmwillis Still think it's ok to add? I'm happy to take it on.

**Comment by Krinkle** [comment]
@ryanto Sounds good to me. Patch welcome!
