### ISSUE TITLE
Add "focus" method to run single test

### ISSUE THREAD

**Issue by timiyay** [qunitjs/qunit#1403]
## Tell us about your runtime:

* **QUnit version**: 2.9.2
* **What environment are you running QUnit in? (e.g., browser, Node)**: browser and Node
* **How are you running QUnit? (e.g., script, testem, Grunt)**: via testem, as part of an Ember app

## What are you trying to do?

I would like to suggest a new `focus` method, as a companion to `skip`. This method is inspired by RSpec's `:focus` tag for inclusion filters: https://relishapp.com/rspec/rspec-core/v/3-8/docs/filtering/inclusion-filters

My use case is:

- I have numerous tests being run, one of which has started failing
- I want to run only that test, to focus on the problem

Currently, I can make use of the filtering by test name in the browser (not sure if this is a QUnit or testem feature), though it can be flow-breaking to figure out the correct strings to use. Not super hard, but not super smooth either.

This is also disruptive when doing Node-based testing, as applying a new filter when in watch mode requires restarting the Ember build.

What I'd love is to be able to change `test()` to `focus()` within my IDE, and have QUnit only run that single test file. If I tried to use `focus()` more than once, it'd throw an error, or perhaps a warning while only running 1 of the tests.

Code that reproduces the problem:

```js
// This test wouldn't be run, nor would any other tests in other files
test('foo', () => {
  assert.equal('foo', 'foo')
})

// I can run only this 1 failing test, and hone in on it
focus('bar', () => {
  assert.equal('bar', 'baz')
})
```

Is this a feature that would be considered useful for others, or does it overlap too much with existing filtering features and issues?

**Comment by platinumazure** [comment]
Hi @timiyay, thanks for the issue.

Does [QUnit.only](https://api.qunitjs.com/QUnit/only) satisfy your use case?

**Comment by timiyay** [comment]
Oh wow, yes that's totally what I want.

I spent 10 minutes grepping source code and Github issues, and I forgot to read the whole docs 🤦‍♂ 

Thanks for your reply, and sorry for the noise.
