### ISSUE TITLE
TAP reporter prints 'Infinity' in a failing test as 'null'

### ISSUE THREAD

**Issue by mathiasbockwoldt** [qunitjs/qunit#1406]
## Tell us about your runtime:

* **QUnit version**: 2.9.2
* **What environment are you running QUnit in?**: Node
* **How are you running QUnit?**: Linux shell (`qunit my_test_file.js`; Linux Mint 19.1; Kernel v. 4.15.0)

## What are you trying to do?

Code that reproduces the problem:

```js
// my_test_file.js
QUnit.test('Infinity test', function(assert) {
    assert.strictEqual(null, Infinity, 'Comparing null and Infinity');
});
```

Run using `qunit my_test_file.js`.

## What did you expect to happen?

I expect to see an error that should look approximately like this. Note the `expected: Infinity`.

```
not ok 1 Infinity test
  ---
  message: "Comparing null and Infinity"
  severity: failed
  actual: null
  expected: Infinity
  stack:     [...]
  ...
```

## What actually happened?

Note the `expected: null`.

```
not ok 1 Infinity test
  ---
  message: "Comparing null and Infinity"
  severity: failed
  actual: null
  expected: null
  stack:     [...]
  ...
```

I don't know much about the internals of QUnit, but this smells JSON conversion.

**Comment by mathiasbockwoldt** [comment]
I researched a little bit more. Not only `Infinity` is shown as `null`, but also `-Infinity` and `NaN`. `undefined` is ok, though (somewhat expected).

```js
// my_test_file.js
QUnit.test('null tests', function(assert) {
	assert.strictEqual(null, Infinity, 'null vs Infinity');
	assert.strictEqual(null, -Infinity, 'null vs -Infinity');
	assert.strictEqual(null, NaN, 'null vs NaN');
	assert.strictEqual(null, undefined, 'null vs undefined');
	assert.strictEqual(null, 0, 'null vs 0');
});
```

Running `qunit my_test_file.js` yiels:

```
TAP version 13
not ok 1 null tests
  ---
  message: "null vs Infinity"
  severity: failed
  actual: null
  expected: null  // should be Infinity
  stack:     [...]
  ...
  ---
  message: "null vs -Infinity"
  severity: failed
  actual: null
  expected: null  // should be -Infinity
  stack:     [...]
  ...
  ---
  message: "null vs NaN"
  severity: failed
  actual: null
  expected: null  // should be NaN
  stack:     [...]
  ...
  ---
  message: "null vs undefined"
  severity: failed
  actual: null
  expected: undefined  // that's ok
  stack:     [...]
  ...
  ---
  message: "null vs 0"
  severity: failed
  actual: null
  expected: 0 // this is of course also ok
  stack:     [...]
  ...
1..1
[...]
```

**Comment by platinumazure** [comment]
Hi @mathiasbockwoldt, thanks for the issue.

Is this only showing up in the TAP reporter? Do you know if the same issue shows up in the HTML reporter?

**Comment by mathiasbockwoldt** [comment]
I just tried it and it looks like it shows as expected in the HTML reporter. I used the example code from qunitjs.com and the test code from my last comment.

![null_tests_html](https://user-images.githubusercontent.com/8100468/65677489-fa6e0d80-e051-11e9-90b5-fc4d10bab0d7.png)

**Comment by platinumazure** [comment]
Thank you @mathiasbockwoldt for doing that test and helping us narrow the issue down to the TAP reporter!

**Comment by Krinkle** [comment]
I suspect this likely due to a JSON serialisation step happening somewhere between QUnit and the TAP reporter we use.

Complex number values like Infinity and NaN are not supported in JSON.

Having said that, since there is no cross-process communication (I think?) there should not be a need to serialise these.

**Comment by Krinkle** [comment]
This might be related to https://github.com/js-reporters/js-reporters/pull/107. Based on that, it seems TAP wants to be given strings to display, which means we may need to stringify these within QUnit first and thus not expose to reporters at all as the native values that they are.

@rwjblue Does that sound right?

**Comment by Krinkle** [comment]
This was fixed upstream by https://github.com/js-reporters/js-reporters/commit/7ec72e30c852ee1ee87ac956e1ac2721fa0a3ccd. I've added a test for it in https://github.com/js-reporters/js-reporters/commit/31ab6e0fbf849bd0.

The issue was indeed the way the TapReporter converted JS values to JSON/YAML.

This will apply to QUnit after the next js-reporters release.
