### ISSUE TITLE
qunitjs.com Cookbook references old "push" method

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1418]
See https://qunitjs.com/cookbook/

In the Custom Assertions section, the "solution" piece references the old "push" method as opposed to "pushResult":

QUnit.assert.contains = function( needle, haystack, message ) {
  var actual = haystack.indexOf(needle) > -1;
  this.push(actual, actual, needle, message);
};

There's also a few hyperlinks surrounding that which point to older (404) API pages.

**Comment by trentmwillis** [comment]
Thanks for reporting! I'll look into getting this fixed soon.
