### ISSUE TITLE
Add a config option for unhandledrejection behavior

### ISSUE THREAD

**Issue by raycohen** [qunitjs/qunit#1419]
I have a large codebase with tests written with QUnit 1. While upgrading, a lot of them fail with QUnit 2.5 because it started considering unhandled rejections errors.

I can probably find a way to work around this, but I was wondering if the QUnit project would support a config option to go back to the old way of allowing unhandled rejections?

**Comment by rwjblue** [comment]
I'm definitely sympathetic to your situation, but I don't think we should have divergent behavior (between `window.onerror` handling and `window.onunhandledRejection` handling) here.

FWIW, as a work around while you work on fixing your test suite you should be able to do something like:

```js
const KNOWN_REJECTIONS = [
  // list of known rejections in your test suite
  // as issues are fixed, you should remove entries
  // from this array
  //
  // the goal here is to ensure that no **knew** unhandled
  // rejections get added to the test suite, while the existing
  // ones are whittled away
];
const ORIG_QUNIT_UNHANDLED_REJECTION = QUnit.onUnhandledRejection;
QUnit.onUnhandledRejection = function(reason) {
  if (KNOWN_REJECTIONS.indexOf(reason.message) > -1) {
    // do nothing
  } else {
    return ORIG_QUNIT_UNHANDLED_REJECTION.call(QUnit, reason);
  }
};
```

**Comment by raycohen** [comment]
No problem. Thanks for the workaround suggestion!

**Comment by NullVoxPopuli** [comment]
properties on `QUnit` are read-only, so this approach is no longer viable.
