### ISSUE TITLE
Running some tests in a specific screen size

### ISSUE THREAD

**Issue by mansona** [qunitjs/qunit#1421]
Hi there, I don't know if this needs to be a feature request or if it's just a request for documentation (or guidance).

We're looking at adding some tests for mobile media queries in our application. We have a series of test helpers to check if something is visible (i.e. if it has `display: none;` or not on the element or any of its parents) but I can't really see any good documentation about defining the screen size of the iframe that our app actually runs in with QUnit 🤔 is this something that is possible?

**Comment by Krinkle** [comment]
@mansona I believe it could be done, in so far that JavaScript is generally allowed to create iframes and/or popups, and you could interact with those frames programmatically from JavaScript to make the necessary assertions.

The QUnit runner is only concerned with loading your test, executing it and listening for your simple comparisons of two JS values, like `assert.equal(isVisible(), true, 'element visibility')`.

Your test would need to create the iframe, navigate to a page in the web app, and determine the visibility of an element. These are built-in capabilities of the HTML/DOM APIs in web browsers that you can call from any QUnit test suite.

However, personally, I think this use-case might be better suited for an end-to-end browser test.

The idea is that you'd have unit tests and integration tests for your JavaScript code in QUnit. And end-to-end browser tests based on Webdriver (e.g. using WDIO) for interactivity and visual confirmation. With WDIO, each test is individually responsible for setting up the browser tab and its size, then navigate to a url within your web app, and then you can directly make assertions about elements on the page. With WDIO, the the test does not run on 1 web page inside the browser, but from an external process that is creating tabs as needed and observe how it behaves.

Doing that with QUnit would mean you either have to change the browser while the test is running (which seems fragile), or use fake browser tabs and work with the complexity of managing those  (iframes), or use a test runner to run the entire test suite multiple times in different browser configurations. The latter could be done from a test runner like [Karma](https://karma-runner.github.io/latest/index.html)
