### ISSUE TITLE
Polling Verifications

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1423]
I am curious of the appetite for such a feature that can poll within verifications, summarized with the following (toy) design case:
```js
// analogous source-under-test
let result = 0;
setTimeout(() => {
  result = 7;
}, 50);

// test code
await assert.eventually(() => result).equal(7, 'reaches threshold');
```
The requirements driving this come from source code that uses timeouts/callback approaches that tests can't directly await, but if they could poll for the result, they could become robust and readable. Often, this comes in the form of interacting with the DOM and allowing for certain elements to update asynchronously. Anti-patterns to this include mysterious setTimeout numbers, coupling implementation details (eg, they used to wait 10ms, so I'll wait for 15ms, but then they upped it to 20ms, failing the test for the wrong reason).

There are 2 approaches I envision, each with different user-experience and architecture:
```javascript
// call methods on an intermediate "pollable" object (scoped namespaces/functionality, but maybe verbose)
await assert.eventually(func).ok([msg])
await assert.eventually(func).notOk([msg])
await assert.eventually(func).equal(expected, [msg])
await assert.eventually(func).notEqual(expected, [msg])

// convenience wrappers (easy, but really widens the assert API)
await assert.eventuallyOk(func[, msg])
await assert.eventuallyNotOk(func[, msg])
await assert.eventuallyEqual(func, expected[, msg])
await assert.eventuallyNotEqual(func, expected[, msg])
```
Those groups of 4 stand out to me as essential, and some of the others may be feasible, but may be gated behind truly "matcher"-style constraint architecture.

I've attached a prototype of the source/test code to demonstrate a couple concepts:
[demo.js.zip](https://github.com/qunitjs/qunit/files/4037683/demo.js.zip)

As well as a screenshot of a run within the browser:
![htmlreport](https://user-images.githubusercontent.com/20109108/72022664-01a2db00-323f-11ea-95fa-7eca6bf1d65b.png)

**Comment by trentmwillis** [comment]
I'm not sure if this is a common enough use case to be added to QUnit itself. I could see this being a valuable extension package that sets up some [custom assertions](https://qunitjs.com/cookbook/#custom-assertions).

**Comment by smcclure15** [comment]
Makes sense; I was on the fence for extension vs core support.
Thanks!
