### ISSUE TITLE
Assertion stack traces off by one in node 12

### ISSUE THREAD

**Issue by evs-chris** [qunitjs/qunit#1430]
When running the qunit cli, I'm getting failed assertions pointing to a line in the qunit.js file that is the stack frame of the assertion method pushing the result rather than the assertion being called. It looks like the issue is that node stacks have an `Error: ` line at the beginning, which misses the [followup skip](https://github.com/qunitjs/qunit/blob/254fccbb34a940334c2001e419f936f4b56db812/src/core/stacktrace.js#L14
) of a first line matching `/^error$/i`.

Based on [this](https://github.com/stacktracejs/error-stack-parser/blob/master/spec/fixtures/captured-errors.js) set of sample stack traces, it looks like `/^(type)?error/i` would cover everything fairly safely, excepting some older flavors of opera, some of which don't have one frame per line anyways.

**Comment by trentmwillis** [comment]
Thanks for the report and link to those sample stack traces.

On a related note, we should start testing against Node 12...
