### ISSUE TITLE
Deprecate "QUnit Git build" on jQuery CDN

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1457]
This is about <https://code.jquery.com/qunit/qunit-git.js> as advertised at <https://code.jquery.com/qunit/>.

For various reasons, this is no longer being updated on a per-commit basis. However after a release we do still have it  as instruction to ensure this updated, which basically means triggering an internal job on our Jenkins server.

I'm proposing that we:
1. Acknowledge that this will remain only for compat and no longer updated on every commit. This is already the case, but since it wasn't done intentionally, I'd like to leave this open for discussion.
2. Update it (via the Jenkins job) only after releases and only for the remainder of QUnit 2.x.
3. After QUnit 3.0 is released, we would remove the Jenkins job, and remove advertised links to this URL, and freeze it in its final 2.x state.

/cc @mgol

**Comment by leobalter** [comment]
Unless we find a security bug in QUnit, I wouldn't worry about updating qunit-git. I'm positive with your current plan.
