### ISSUE TITLE
Build failing with 2.11.0 nexus not found

### ISSUE THREAD

**Issue by SaumyaShekhar** [qunitjs/qunit#1473]
http://nexus.wdf.sap.corp:8081/nexus/repository/build.milestones.npm/qunit/-/qunit-2.11.0.tgz: Request failed \"404 Not Found\"".

**Comment by Krinkle** [comment]
It was uploaded yesterday to the npm registry via <https://www.npmjs.com/package/qunit/v/2.11.0> and is available through package.json and the `npm` command if using the default registry at `registry.npmjs.org`.

It looks like you might be using a private proxy controlled by your company. Perhaps it has a delay or perhaps it requires manual copying or importing of new packages. You may need to ask your IT administrator to do that.

**Comment by Krinkle** [comment]
Closing this for now, do let me know if there's anything we can do to help!
