### ISSUE TITLE
[Feature] Rerun all failed tests

### ISSUE THREAD

**Issue by buschtoens** [qunitjs/qunit#1474]
I often find myself wanting just rerun all failed tests, no matter what module they're from. The use case is changing a central piece in a large application, that causes test failures in a lot of places. While fixing these, I would like to focus on the failed tests only and avoid rerunning the full test suite.

I currently evaluate this snippet in the DevTools console to generate such a link:

```js
location.origin + '/tests?testId=' + [
  ...document.querySelectorAll('.fail[id^="qunit-test-output"]')
].map(n => n.id.slice('qunit-test-output-'.length)).join('&testId=')
```

I think adding a proper button for this would be immensely useful.

**Comment by Krinkle** [comment]
Sounds good to me!

Note that QUnit by default remembers failed tests in `sessionStorage`, and upon refresh those will always run first. But having a dedicated link for this sounds good to me. This will have the small caveat that if other tests start failing, you won't notice until you re-run all tests. Whereas if you use the default reordered-failed-first behaviour you both get quick results and still get the rest run in the background.

I'd recommend adding this  button at the end of the status message where it says "1 assertions of 2 passed, 1 failed."

**Comment by buschtoens** [comment]
I finally got annoyed enough to implement this: #1626 😄
