### ISSUE TITLE
Build: transpile nullish operators and optional chaining

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1497]
What is the appetite to incorporate Babel transpiling of [nullish coalescing operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) (??) and [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (?.) ?

**Comment by Krinkle** [comment]
I'm somewhat leaning to removing Babel once we drop IE11 support and then use/require ES6 natively, and newer capabilities in sync with the browsers we support.

As such I'd slightly prefer not to emulate more syntax features. If some of these can be brought in via a conditional polyfil or utility function, though, that would be more appealing.

Having said that, I don't feel strongly about it 🙂  – It's just a general direction I have in mind at the moment.

**Comment by smcclure15** [comment]
That sounds fair. Maybe I'm too eager to see old browsers drop off...
I figure if we can opportunistically write modern code today, we should, and let the transpile step support the oldest environment that we need to. Then when those drop, the code doesn't change - we just drop the transpilation. I do remain hesitant on experimental feature support - that can introduce some debt/instability that we don't need.

**Comment by Krinkle** [comment]
@smcclure15 I think we're in agreement. What I'm trying to avoid however is an indefinite hold-off where we're always waiting for the promise of a simpler stack that never arrives due to there always being another thing just over the horizon, so I'm trying to be a little bit more selective now so that we can start spending time on the other side of that horizon. Once there, we can adopt things as we see fit based on browser support, without that additional complexity.

**Comment by smcclure15** [comment]
Sounds good, and thanks for taking the time to explain your rationale. I agree with the desire to avoid unnecessary churn and delay building up.

As a new member (thanks!), let me know if there’s anything I can do to support the effort on the 3.0 milestone, or it’s relevant timelines. I’ve recently indulged in dropping old browser support with my employer, and it’s been liberating from an infrastructure standpoint.

**Comment by Krinkle** [comment]
@smcclure15 Awesome. Couple of things to look at: 
* Release 2.x milestone: https://github.com/qunitjs/qunit/milestone/11
* Release 3.0 roadmap: https://github.com/qunitjs/qunit/issues/1498

Also, if you like, feel free to join the [Chat room](https://gitter.im/qunitjs/qunit).
