### ISSUE TITLE
HTML reporter scrolls the test summary off the top as tests run

### ISSUE THREAD

**Issue by BryanCrotaz** [qunitjs/qunit#1512]
When running a large test suite the tests push the headers off the top of the window. If you have a lot of failures and want to give up the run and filter the test set, every time you scroll up to the headers, the next test failure pulls you back to the bottom. Very frustrating.

With PR #1513 the headers are fixed at the top with flexbox and the tests scroll within their own area. Problem solved.

**Comment by BryanCrotaz** [comment]
As this is a non-breaking change, can it go into a 1.x release rather than waiting for the other 2.x stuff?

**Comment by Krinkle** [comment]
@BryanCrotaz The current release is 2.x, the "next" release milestone is 3.x (which will only remove a few deprecated methods and raise browser requirements). The 1.x line has not been active since 2016.
