### ISSUE TITLE
(meta) 2.14.0 Release notes refer to incorrect issue

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1547]
The latest 2.14.0 release has a few release notes:
https://github.com/qunitjs/qunit/releases/tag/2.14.0

However, the "HTML Reporter: Set main and navigation ARIA roles" note should refer to #1427 instead.

**Comment by Krinkle** [comment]
Oops. I've fixed the release text now. Thanks!

I think the same mistake is in the History file as well.
