### ISSUE TITLE
ESM build

### ISSUE THREAD

**Issue by matthewp** [qunitjs/qunit#1551]
An ESM build would be nice given that browser support for modules is mature these days.

Currently to use modules when testing with QUnit I do something like this:

```html
<script src="https://code.jquery.com/qunit/qunit-VERSION.js"></script>
<script type="module" src="./test.js"></script>
```

__local_qunit.js__

```js
export default window.QUnit;
```

__test.js__

```js
import QUnit from './local_qunit.js';
```

Given that qunit is using rollup for the build it should be relatively straight-foward to add a second build output for use with `<script type="module">` so you would be able to do:

```js
import QUnit from 'https://code.jquery.com/qunit/qunit-VERSION.mjs';

...
```

**Comment by Krinkle** [comment]
@matthewp There shouldn't be any need to bring the QUnit object in as a module import. It is meant to bootstrap the HTML page for you and takes care of itself. The test suites should reference `QUnit` API as a host variable, similar to how you might interact with `window`, `location`, `URL` etc.

Could you explain what problem or advantage you are currently addressing by using QUnit in this way? I'd prefer not to maintain multiple build outputs, but I could consider it or come up with simpler solutions, if I understood the use case better. Thanks!

**Comment by matthewp** [comment]
Maybe I'm not following but I need to reference the QUnit object to do:

```js
QUnit.test('my test')....
```

The advantage to it being available as a module is the same as for any module.

**Comment by Krinkle** [comment]
@matthewp The `QUnit` object is always available. Does it not work from your ESM-loaded `test.js` file?

**Comment by reno1979** [comment]
Same problem here. 

Test modules that require QUnit al import QUnit, and I need to build them before the can be used.

**Comment by matthewp** [comment]
@Krinkle Yeah maybe I wasn't being clear about my reasoning here. Yes, QUnit works fine as a global via a classic script tag. There's nothing that doesn't work about it. It's just that I would rather my modules explicitly import their dependencies and not rely on external dependency management (having to remember to always include a script tag in the right order on the page). So the reason to have QUnit be a module is the same reason to have *any* dependency to be a module.

**Comment by Krinkle** [comment]
This will also resolve https://github.com/qunitjs/qunit/issues/1724 once done.

**Comment by Krinkle** [comment]
Quoting here to ease discovery.

From https://github.com/qunitjs/qunit/issues/1729#issuecomment-2177241785:
> […]
> 
> I'd like to make it safe in QUnit 3.0 to load qunit.js multiple times. Today we consider this an error and throw an error. To adopt ESM we will likely have to provide a separate build. For projects that reference QUnit globally, with one part of the test stack responsible for actually loading it, this will work fine. They can switch or not switch depending on their needs and requirements, it's fine either way.
> 
> For projects that reference QUnit by importing it in individual plugins, integration layers, and/or test files, there's a good chance that there will be mixed use in practice. If we don't do anything to prevent it, this will cause various split-brain problems where config/plugins are missing, or tests are divided, event handlers firing multiple times, etc. This also came up in discussions for jQuery at [jquery/jquery#5429](https://github.com/jquery/jquery/pull/5429) where similar concerns were raised. For QUnit, we're a bit more flexible in some ways and less flexible in others.
> 
> I'm thinking of making QUnit safe to load multiple times. We're not concerned about clashing versions of QUnit. These are going to be the same version. Whichever loads first will own the state, and subsequent imports (e.g. CJS first then ESM, or vice versa) will effectively resume that instead of exporting a different local copy.
> 
> […]

**Comment by Krinkle** [comment]
Summary of recent changes, mostly around getting `core.js` into a shape where it "just" exports stuff simply and straight-forwardly, in a way we can convert and expose as ESM, and easily explain/document as such:

* Core: Export `QUnit.urlParams` unconditionally. https://github.com/qunitjs/qunit/commit/57c2dbcffc694bf3a0b5d1d57e7f43f16ff29862
* HTML Reporter: Refactor as class without side-effects, export `HtmlReporter` as `QUnit.reporters.html`. https://github.com/qunitjs/qunit/commit/e1e03e68df788c013a7ccdc8ec1cc4aff33ec600
* Browser Runner: Refactor to side-effect free file, simply call conditionally in the entry point file. https://github.com/qunitjs/qunit/commit/6a8318a23aa303c37fdf92b2497002d868811222
* Test: Remove reliance on subtle export/require details. https://github.com/qunitjs/qunit/commit/57a543bdfc6d8aa546a4834fd2127de0b0347289
* Core: Remove reliance on Rollup's extension-less imports. Make `src/` compatible with ESM in Node.js as-is. https://github.com/qunitjs/qunit/commit/95105aad6200f844d78bdb240c618d95b869f06e
* Core: Reduce `src/core.js` to a single object literal. No more indirect assignments or extensions. https://github.com/qunitjs/qunit/commit/d39552565b15d37dd04f66108a593014e90711f1
