### ISSUE TITLE
Contextual assertion messages

### ISSUE THREAD

**Issue by ro0gr** [qunitjs/qunit#1570]
I'm exploring some better ways for integrate page objects with qunit. There are few areas to improve, but the point of this ticket is to improve default experience for the assertion messages.

Let's say, each page object property is a JS object, which has a `valueOf(` defined. The responibility of the `valueOf(` is to query DOM for some value, when the page object node is accessed:

```js
const MyForm = {
  myInput: {
    selector: '.myInput',
    valueOf() {
      return document.querySelector(this.selector).value;
    }
  }
};

assert.equal(MyForm.myInput, 'some value');
```

This does almost work fine, but the final assetion message lacks any contextual information, and would look like `ok` in case of success, and `failed` in case of a failure, until I pass an explicit assetion message as the third argument of the `equal(`.

I believe it'd be really nice to provide an ability to use the `actual` context, in order to build a more precise assertion message, so it could look like:

> Element ".myInput" expected to be equal to "some value".

The knowledge about page objects seems to be a bit too much for the "qunit". However, I'm curious if we can provide some minimal API, to build assertion messages in the user land?

I can think of some kind of a global configuration, like:
```ts
// this type is highly inspired by the pushResult signature.
// It does not have a `result`, cause it seems fine to have an assertion message stable, since it's colored properly by reporter.
// It does also miss a `message`, since the `defaultMessage` handler should be called only if there is no user `message` provided.
// However, it includes a new `assertionKind` property, which allows to distinct between an actual assertion kind, and build a more precise assertion message.
type AssertionMeta = {
  actual: Descriptor;
  assertionKind: 'equal'|'ok'|'strictEqual';
  expected: any;
  negative: boolean;
};

QUnit.config.defaultMessage = (assertionMeta: AssertionMeta): string | undefined => {
  const { actual, assertionKind, expected, negative } = assertionMeta;

  if (isPageObject(actual)) {
    if (['equal'|'ok'|'strictEqual'].includes(assertionKind)) {
      return `Element "${actual.selector}" expected to be ${negative ? 'not' : ''} equal to "${expected};".`
    }
  }
  
  return; // in case of `undefined` the default "ok"|"failed" messages are applied
}
```

Please let me know if an integration like this makes sense for the "qunit". I'd be glad to iterate on this and find a good solution. Thanks!

**Comment by Krinkle** [comment]
Thanks for reporting. Having a better default here makes a lot of sense to me.  I think people would usually register an assertion plugin for this purpose. Could you give that a try?

See <https://api.qunitjs.com/assert/pushResult/> for an example. You can then define your own description message and/or "expected value" rendering. Personally I tend to place it in the expected value, but you could also append some or all of it to the message indeed.

**Comment by ro0gr** [comment]
Thanks for your quick response.

> I think people would usually register an assertion plugin for this purpose. 

Do you mean to use an assertion plugin in order to create a new asserion, or even override an existing one, right?

I think, I'm looking for a way to re-use the built-in assertions, so I don't need to re-implement each assertion on the consumer side just because of a default `message` for the page objects case.

Though, I can try _(going to do it)_ to wrap the `pushResult(`, in order to prebuild a `message`, if missing. However, looks like we'd still miss an important part, which would help us to distinct between the kinds of assertions(`equal`, `between`, `includesText`,...), smth like `assertionKind` mentioned above, so a more precise message could be generated for each specific assertion. Do you think there is a chance to consider adding smth like `assertionKind` option to the `pushResult(`?
 
> Personally I tend to place it in the expected value

Yes, this is a good point to consider. However, my exact issue, which I'd like to address here is a miriad of anonymous `okay`s and `failed`s in the test output, which happens when an assertion hasn't been provided with a `message` on the invocation side.

**Comment by Krinkle** [comment]
@ro0gr The way I would do it is to register a variant of the assertion method(s) that you're interested in. I think there would only be one or two in practice, right?

For example, if you wanted a dedicated assertion method that takes a PageObject for an input element of some kind, and asserts its current value:

```js
const MyForm = {
  myInput: {
    selector: '.myInput',
    valueOf() {
      return document.querySelector(this.selector).value;
    }
  }
};

assert.pValueEqual(MyForm.myInput, 'some value');
```

Where `pValueEqual()` could be defined as:

```js
QUnit.assert.pValueEqual = function (p, expected, message) {
	const actual = p.valueOf();
	this.pushResult({
		result: expected === actual,
		actual,
		expected,
		`value of element "${p.selector}" element. ${message}`
	});
};
```

And could produce results such as:

```diff
Search: suggestions field

   1. value of "#p-search input" element. initial
   2. value of "#p-search input" element. pressed P
   3. value of "#p-search input" element. after selecting first suggestion
+     Expected: Public domain
-     Actual:   Prince Philip, Duke of Edinburgh
```

Having said all that, I personally avoid using plugins like this. They tend to be harder to discover for new contributors to a project, might get naming clashes, and probably have suboptimal pressures with regards to naming brevity vs understandability. And while I tend to only use `strictEqual()` for new code, you did mention other methods and yeah, you'd need a variant for each one.

If you're curious about how others address this, or how I would do it, then we may need a more complete example to understand the issue you want to address. As I see your current example, I feel like that's quite good as it is. I'm not sure I'd want the selector to be in the test output in that case, if the test is mainly about constructing the search form component and checking its input field, then assertion messages like `initial value` and `value after selecting first suggestion` seem useful enough, or even more useful (less noise) since the selector seems less relevant in that case. Anyway, I'm sure the selector is useful to you if thats what you are looking for. It just means I probably haven't quite understood the larger picture. Happy to help more if you offer more details. Or perhaps the above suffices if writing a plugin works for you.

**Comment by Krinkle** [comment]
I'm actually curious why the selector is important to you. Your example is probably simplified, so perhaps you can share a bit more to help me understand it better?

The way I'm currently thinking, is, if this is a test for a specific UI component, it probably has a descriptive name of the widget in its test name, and the word "value" or "input value" would suffice to explain what the assertion is about.

But, for now here's a few different ideas to consider:

### Simple plugin

If you want to go with the plugin way, the way I would do it is to register a variant of the assertion method(s) that you're interested in. In practice, I think `strictEqual`-like behaviour would suffice for most tests (I wrote a [blog post](https://timotijhof.net/posts/2015/qunit-anti-patterns/) about avoiding `equal` and `ok` in new tests).

Dedicated assertion method that accept PageObject for an input element, and asserts its current input value:

```js
const MyForm = {
  myInput: {
    selector: '.myInput',
    valueOf() {
      return document.querySelector(this.selector).value;
    }
  }
};

assert.pValueEqual(MyForm.myInput, 'some value');
```

Where `pValueEqual()` could be defined as:

```js
/** @param {PageObject} p */
QUnit.assert.pValueEqual = function (p, expected, message) {
	const actual = p.valueOf();
	this.pushResult({
		result: expected === actual,
		actual,
		expected,
		`value of "${p.selector}" element. ${message}`
	});
};
```

And could produce results such as:

```diff
Search: suggestions field

   1. value of "#p-search input" element. initial
   2. value of "#p-search input" element. pressed P
   3. value of "#p-search input" element. after selecting first suggestion
+     Expected: Public domain
-     Actual:   Prince Philip, Duke of Edinburgh
```

### Ambitious plugin

If you really like going the plugin way, but want to have less awkward names for the method, you could go for a Fluent interface. Many libraries are modelled like this.

```js
// search-test.js
assert.page(MyInput).value('Public domain', 'selected suggestion');

// testutils.js
class PageObjectAssertion {
  constructor(assert, p) {
    this.assert = assert;
    this.p = p;
  }
  value(expected, message = '') {
   const actual = this.p.valueOf();
    this.pushResult({
      result: expected === actual,
      actual, expected,
      `value of "${p.selector}" element. ${message}`
    });
  }
}
  
QUnit.assert.page = function (p) {
  return new PageObjectAssertion(p, this);
};
``

-------

For me personally, I rarely write assertion plugins. I prefer to use only the built-in assertions and use them directly in tests. I usually avoid abstractions within tests where possible, or perhaps reach for a utility function that feeds into the assertion methods, instead of abstracting them away. Something like this perhaps:

### Assertion utility

These are easier to import and give short/contextual names to.

```js
// testutils.js
function value(assert, selector, expected, message) {
   const actual = document.querySelector(this.selector).value;
   assert.strictEqual(actual, expected, `value of "${p.selector}" element. ${message}`);
}

// search-test.js
const INPUT = "#p-search input";
QUnit.test('Search form', assert => {
  value(assert, INPUT, '', 'initial value');
  value(assert, INPUT, 'p', 'pressed P');
  value(assert, INPUT, 'Public domain', 'after selection');
```

### General utility function

Sometimes placing it in the test name is enough.

```js
// search-test.js
const INPUT = "#p-search input";

QUnit.test(`Search form: Interaction with ${INPUT}`, assert => {
  const element = document.querySelector(INPUT);
  assert.equal(element.value, '', 'initial value');
  assert.equal(element.value, 'p', 'pressed P');
  assert.equal(element.value, 'Public domain', 'after selection');
```

Or if the value is complex to access:

```js
// testutils.js
function value(selector) {
      return document.querySelector(this.selector).value;
}

// search-test.js
const INPUT = "#p-search input";
QUnit.test(`Search form: Interaction with ${INPUT}`, assert => {
  assert.equal(value(INPUT), '', 'initial value');
  assert.equal(value(INPUT), 'p', 'pressed P');
  assert.equal(value(INPUT), 'Public domain', 'after selection');
```

I hope some of that is useful!

**Comment by Krinkle** [comment]
I'm actually curious why the selector is important to you. Your example is probably simplified, so perhaps you can share a bit more to help me understand it better?

The way I'm currently thinking, is, if this is a test for a specific UI component, it probably has a descriptive name of the widget in its test name, and the word "value" or "input value" would suffice to explain what the assertion is about.

But, for now here's a few different ideas to consider:

### Simple plugin

If you want to go with the plugin way, the way I would do it is to register a variant of the assertion method(s) that you're interested in. In practice, I think `strictEqual`-like behaviour would suffice for most tests (I wrote a [blog post](https://timotijhof.net/posts/2015/qunit-anti-patterns/) about avoiding `equal` and `ok` in new tests).

Dedicated assertion method that accept PageObject for an input element, and asserts its current input value:

```js
const MyForm = {
  myInput: {
    selector: '.myInput',
    valueOf() {
      return document.querySelector(this.selector).value;
    }
  }
};

assert.pValueEqual(MyForm.myInput, 'some value');
```

Where `pValueEqual()` could be defined as:

```js
/** @param {PageObject} p */
QUnit.assert.pValueEqual = function (p, expected, message) {
	const actual = p.valueOf();
	this.pushResult({
		result: expected === actual,
		actual,
		expected,
		`value of "${p.selector}" element. ${message}`
	});
};
```

And could produce results such as:

```diff
Search: suggestions field

   1. value of "#p-search input" element. initial
   2. value of "#p-search input" element. pressed P
   3. value of "#p-search input" element. after selecting first suggestion
+     Expected: Public domain
-     Actual:   Prince Philip, Duke of Edinburgh
```

### Ambitious plugin

If you really like going the plugin way, but want to have less awkward names for the method, you could go for a Fluent interface. Many libraries are modelled like this.

```js
// search-test.js
assert.page(MyInput).value('Public domain', 'selected suggestion');

// testutils.js
class PageObjectAssertion {
  constructor(assert, p) {
    this.assert = assert;
    this.p = p;
  }
  value(expected, message = '') {
   const actual = this.p.valueOf();
    this.pushResult({
      result: expected === actual,
      actual, expected,
      `value of "${p.selector}" element. ${message}`
    });
  }
}
  
QUnit.assert.page = function (p) {
  return new PageObjectAssertion(p, this);
};
```

-------

For me personally, I rarely write assertion plugins. I prefer to use only the built-in assertions and use them directly in tests. I usually avoid abstractions within tests where possible, or perhaps reach for a utility function that feeds into the assertion methods, instead of abstracting them away. Something like this perhaps:

### Assertion utility

These are easier to import and give short/contextual names to.

```js
// testutils.js
function value(assert, selector, expected, message) {
   const actual = document.querySelector(this.selector).value;
   assert.strictEqual(actual, expected, `value of "${p.selector}" element. ${message}`);
}

// search-test.js
const INPUT = "#p-search input";
QUnit.test('Search form', assert => {
  value(assert, INPUT, '', 'initial value');
  value(assert, INPUT, 'p', 'pressed P');
  value(assert, INPUT, 'Public domain', 'after selection');
```

### General utility function

Sometimes placing it in the test name is enough.

```js
// search-test.js
const INPUT = "#p-search input";

QUnit.test(`Search form: Interaction with ${INPUT}`, assert => {
  const element = document.querySelector(INPUT);
  assert.equal(element.value, '', 'initial value');
  assert.equal(element.value, 'p', 'pressed P');
  assert.equal(element.value, 'Public domain', 'after selection');
```

Or if the value is complex to access:

```js
// testutils.js
function value(selector) {
      return document.querySelector(this.selector).value;
}

// search-test.js
const INPUT = "#p-search input";
QUnit.test(`Search form: Interaction with ${INPUT}`, assert => {
  assert.equal(value(INPUT), '', 'initial value');
  assert.equal(value(INPUT), 'p', 'pressed P');
  assert.equal(value(INPUT), 'Public domain', 'after selection');
```

I hope some of that is useful!

**Comment by ro0gr** [comment]
@Krinkle

> I'm actually curious why the selector is important to you.

I've just used selectors as an example of some contextual information which can be useful in assertion messages. For instance, if some assertion fails, you could copy-paste a selector from the error message, and try to look up a broken Element in the dev tools to start the investigation.

> if this is a test for a specific UI component, it probably has a descriptive name of the widget in its test name, and the word "value" or "input value" would suffice to explain what the assertion is about.

Yeah, this is correct. If we had an ability to customize default messages(and if the #1596 makes sense), it'd be possible to also add the name of the page object property which is used in the assertion.

> Ambitious plugin

We've [explored](https://github.com/yratanov/ember-page-object-asserts) a similar direction a while ago, but at the end I think this is much a heavier solution than we really need.

> For me personally, I rarely write assertion plugins. 

Me too! I'm a big fan of a single assertion for equality. That's why I'm looking for an integration story with the QUnit assertions itself at the first place.

> I think strictEqual-like behaviour would suffice for most tests

Yeah, I wish I could use `strictEqual(`! And in my case there is a problem, for which I've created a ticket(#1596). 

To be clear, I think #1596 is a precondition for this issue about the assertion messages _(yeah, I should have created the issues in a reverse order)_. In case, if boxed primitives support doesn't make sense for the QUnit, I'd close the current issue, cause, otherwise, the best I could have, even with the customizable assertion messages, is the `assert.equal(`. So in this case the best option I can think of is a custom assertion like `valueOfStrictEqual(`.

**Comment by Krinkle** [comment]
@ro0gr One more idea came to mind, to blend the helper classes you currently have, with the above "Assertion utility" approach:

```js
// testutils.js
function Helper {
  constructor(selector) {
    this.selector = selector;
  }
  get value() {
    return document.querySelector(this.selector).value;
  }
  get msg() {
   return `value of "${this.selector}"`;
  }
  // Or, to support prepending your own message:
  // msg(message = '') {
  //  return (message ? `${message}\n` : '') + `Selector: ${this.selector}`;
  // }
}
function wrap(selector) {
  return new Helper(selector);
}

// search-test.js
QUnit.test('Search form', assert => {
  const myInput = wrap('#p-search input')
  assert.strictEqual(myInput.value, '', myInput.msg);
  // press P
  assert.strictEqual(myInput.value, 'Public domain', myInput.msg);
```
