### ISSUE TITLE
Accept array for hooks

### ISSUE THREAD

**Issue by Yash-Singh1** [qunitjs/qunit#1624]
Maybe QUnit.module could also accept an array of functions for its hooks

**Comment by Krinkle** [comment]
@Yash-Singh1 Thanks for opening this issue.

I'd like to know a little bit more about your specific circumstances to make sure we're doing the best we can to solve the problem rather than implement specific ideas directly.

What is leading you to develop these as separate functions? Could you share an example of where you'd like to use this?

**Comment by Yash-Singh1** [comment]
I have a function named `clean`, that cleans up all of the files that would affect the current or further tests. Here is the code so far:

```js
function clean() {
  // code for cleaning all the stuff
}

QUnit.module('abc', {
  before: clean,
  after: clean
})
```

I also have another job that I want to run only in the `before` hook. If there is some syntax for applying multiple functions to a hook, then I can do something like:

```js
function clean() {
  // code for cleaning all the stuff
}

function otherJob() {
  // code that will run the other job
}

QUnit.module('abc', {
  before: [clean, otherJob],
  after: clean
})
```

But, what I have to do is:

```js
function clean() {
  // code for cleaning all the stuff
}

function before() {
  clean()
  // code that will run the other job
}

QUnit.module('abc', {
  before,
  after: clean
})
```

**Comment by Krinkle** [comment]
@Yash-Singh1 Thanks, that makes sense.

I'll show you a couple of existing patterns we support. Perhaps you see something new here that would work for you?

1. Inline calls.

This uses the same flat-module style and options object as you currently use, but with function calls moved to an inline wrapper. This makes it feel a bit simpler, and is effectively an array in function format.

```js
function clean() {}
function other() {}

QUnit.module('abc', {
  before() {
    clean();
    other();
  },
  after() {
    clean();
  }
});
```

2. Hooks parameter.

In QUnit 1.20, support for multiple hooks was introduced via the `hooks` parameter. In the below example, I use the [scoped module](https://api.qunitjs.com/QUnit/module/#example-hooks-on-nested-modules) pattern.

Calling `hooks.before()` is internally appending to an array for you. You can even nest modules inside each other (e.g. "Module: Feature", and "Module: Feature with X"), and then the inner module will automatically inherit the same hooks.

```js
QUnit.module('foo', hooks => {
  hooks.before(clean);
  hooks.before(other);
  hooks.after(clean);

  QUnit.test('walk', assert => {});

});
```
```js
QUnit.module('foo', hooks => {
  // …

  QUnit.module('foo with bar', hooks => {
     hooks.before(extraBarSetup);

     QUnit.test('run', assert => {});

  });
});
```

2. Scoped variables.

You can also use scoped variables, like so:

```js
QUnit.module('foo', hooks => {
  let foo;
  // …
  hooks.beforeEach(() => {
    foo = new Foo();
  });

  QUnit.module('foo with bar', hooks => {
     let bar;
     hooks.beforeEach(() => {
       bar = new Bar(foo);
     });

     QUnit.test('run', assert => {});

  });
});
```

3. Array map.

This one is not officially documented right now, but if you prefer to control the array directly, then this could work. I do not recommend it right now, but it is something you could use today if it avoids a certain problem. That might also help me to better understand it :)

```js
QUnit.module('abc', hooks => {
  [clean, otherFoo].map(hooks.before);
  [clean].map(hooks.after);

  QUnit.test('foo', assert => {});

});
