### ISSUE TITLE
assert.throws can succeed if actual value is not a function and no matchers are used

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1637]
I noticed that passing something like "1" into the `throws` assertion actually passes:

```js
assert.throws(1);
// or
assert.throws(1, 'succeeds');
```

What's actually going on is shown if you use a matcher:
```js
assert.throws(1, /somematch/);
```
```
  message: fails
  severity: failed
  actual  : TypeError: block.call is not a function
  expected: "/somematch/"
```

Which is what is used to invoke the actual function inside a try/catch block. So this is true for really anything that isn't a function:
```js
assert.throws(undefined, 'succeeds');
assert.throws(undefined, /somematch/, 'fails');

assert.throws('notafunction', 'succeeds');
assert.throws('notafunction', /somematch/, 'fails');

assert.throws([], 'succeeds');
assert.throws([], /somematch/, 'fails');

assert.throws({}, 'succeeds');
assert.throws({}, /somematch/, 'fails1');
```

On one hand, sure, when the actual value is invoked, an exception is thrown. But I think this has the potential of false-positives; passing tests but it's really hiding something there. Even something like the following now has me second-guessing and desiring more validation (maybe asserting`typeof` ahead of the throws check?):
```js
let myfcn = utils.myFunctionGenerator();
assert.throws(myfcn)

let myfcn2 = utils.myFunctionGenerator(config);
assert.throws(myfcn2)
```

I'm proposing something more explicit for this case...

**As a summary spec, `throws` shall:**
* pass if the actual value is a function, which throws, and the expected value is undefined
* pass if the actual value is a function, which throws, and the expected value "matches"
* fail if the actual value is a function and does not throw
* **(NEW) fail if the actual value is not a function**
* error if the expected value is invalid (#1635)

The new item would more align with the `rejects` validation that the actual value must be a promise (or thenable).

**Comment by Krinkle** [comment]
Agreed fully. I propose we deprecate this along with the invalid `expected` values, possibly in the same patch if you like.
