### ISSUE TITLE
No way to watch .ts tests

### ISSUE THREAD

**Issue by BryanCrotaz** [qunitjs/qunit#1669]
```json
"scripts": {
    "build": "tsc src/index.ts",
    "dev": "tsc src/index.ts --watch",
    "test": "qunit --require ts-node/register --watch 'test/**/*-test.ts'"
  }
```

Easy to run typescript tests, and pretty well documented. However `--watch` only reruns tests when `.js` files change. It ignores `.ts`files.

Suggestion: watch should trigger on both ts and js files.

**Comment by Krinkle** [comment]
Thanks, I would expect that to work as-is indeed.

The code for this is in `src/cli/run.js` as called from `bin/qunit`. We currently evaluate the glob pattern during the runs (initial and re-run from watch), which means that new files matching the pattern are naturally picked up. The watcher subscribers to the working directory as a whole. The watcher does not limit itself to the glob pattern, as we want to watch based on any of the source files as well. It currently ignores changes to `node_modules` or non-JS files.

One way to handle this could be to remember the `files` list from the last run, and if the watcher tells us about a changed file in that list, also start a re-run. The downside would be that this doesn't cover `.ts` source files, only test suites.

Another way could be to inspect `require.extensions` keys and take those extensions into consideration. This would be `.js` and `.json` by default, and `ts-node` adds `.ts` to this.

Patch welcome. I might also give it a go myself during the next release in ~12 days.
