### ISSUE TITLE
cli: accept a `module` flag/other flags

### ISSUE THREAD

**Issue by ShaMan123** [qunitjs/qunit#1680]
Another thing is that the cli should accept a `module` flag and set `QUnit.config.module` to the passed value
It's an easy fix, I would PR but I don't understand where the file is located.

_Originally posted by @ShaMan123 in https://github.com/qunitjs/qunit/issues/1671#issuecomment-1045203732_

If I'm right this should be an easy fix:
https://github.com/qunitjs/qunit/blob/e91441eaf302d427c0c3a49ea1fc8d9ab61cb611/src/cli/run.js#L27

**Comment by Krinkle** [comment]
Closed by https://github.com/qunitjs/qunit/commit/924e0227c3ba77569cc30ce2ab607873c194d93d.
