### ISSUE TITLE
How to avoid "Unexpected test after runEnd." warning when using dynamic imports in test.html

### ISSUE THREAD

**Issue by i94alan** [qunitjs/qunit#1694]
* **QUnit version**: 2.17.0
* **Which environment are you using? (e.g., browser, Node)**: browser
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: manually in browser

## What are you trying to do?
Originally, I run parent.js with qunit.js in a test.html: with qunit-2.16.0

```html
<!DOCTYPE html>
<html>
<head>
...
</head>
<body>
    <div id="qunit"></div>
    <div id="qunit-fixture"></div>
    <script src="third_party/qunit/qunit-qunit-2.16.0.js"></script>
    <script type="module" src="parent.js"></script>
</body>
</html>
```

parent.js uses dynamic import to import child1.js and child2.js which contain Qunit tests, and they are executed successfully.

Now,

I upgrade Qunit to 2.17.0, then Qunit test in child1.js and child2.js has this problem:
`qunit.js:2843 Unexpected test after runEnd. This is unstable and will fail in QUnit 3.0.`

BUT, if I use static import for child1.js and child2.js, their test will be executed successfully.

Question: Can QUnit 2.17.0 support dynamic import of a Javaacript Qunit test files( in my case, child1.js, child2.js). If it does not support dynamic import, then I will have to test child1.js and child2.js with static import:

```html
<!DOCTYPE html>
<html>
<head>
...
</head>
<body>
    <div id="qunit"></div>
    <div id="qunit-fixture"></div>
    <script src="third_party/qunit/qunit-qunit-2.16.0.js"></script>
    <script type="module" src="parent.js"></script>
    <script type="module" src="child1.js"></script>
    <script type="module" src="child2.js"></script>
</body>
</html>
```

**Comment by Krinkle** [comment]
@i94alan Yes, you can use `QUnit.config.autostart` to let the test runner know when you are done loading test files.

See https://api.qunitjs.com/config/autostart/ for an example.

Basically:

```js
// test/parent.js
QUnit.config.autostart = false;

Promise.all([
  import('./foo.js'),
  import('./bar.js')
]).then(function () {
  QUnit.start();
});
```

**Comment by Krinkle** [comment]
I've added the above example with dynamic imports to <https://api.qunitjs.com/config/autostart/>, with mention of the warning you got so that it'll be discoverable for the next person.

Thank you for asking!
