### ISSUE TITLE
Can we start a `next` branch so I can start PRing improvements?

### ISSUE THREAD

**Issue by NullVoxPopuli** [qunitjs/qunit#1730]
I was thinking a `next` branch would be good because otherwise `main` would either:
- be unreleasable while we bundle up all the improvements for a single major
- would be releasable but we'd maybe need to go through multiple majors if "something needs to go out"

thoughts?

**Comment by Krinkle** [comment]
Done. I'm currently working on finishing up deprecations and API changes for 3.0, as well as fixing integrations to not use deprecated APIs. That'll iterate on main for a few more weeks at least.
