### ISSUE TITLE
Fix logo for QUnit (font inconsistency)

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#222]
QUnit has had a jQuery-style logo as icon for a long time now, that's OK. But I couldn't find any with the correct text and perhaps tag line. The first time I saw the name composed next to it was on the new website, but that looks out of place:

![jQuery logo](http://i.imgur.com/zFhWv.png) ![jQuery Mobile logo](http://i.imgur.com/nzMzz.png)

![jQuery UI logo](http://i.imgur.com/DOBdx.png)

![QUnit logo](http://i.imgur.com/z7c4Y.png)

Would be nice if someone could create a Vector graphic with the QUnit name next to it in the right font. And some kind of tagline perhaps, not sure if there is one (or just leave it off..).

**Comment by aleen42** [comment]
So, is there any `.svg` file or `.ai` for QUnit? And I want to make a badge for it in the repository [**badges**](https://github.com/aleen42/badges)

**Comment by trentmwillis** [comment]
@aleen42 you can download `.eps` versions of the logo with the jQuery Foundation logo suite here: https://brand.jquery.org/logos/#the-mark
