### ISSUE TITLE
assert.equal: Order of expected and actual output

### ISSUE THREAD

**Issue by drosowski** [qunitjs/qunit#407]
Hi there,
is there a reason for choosing another order of expected and actual values as opposed to the existing xunits like JUnit or phpunit? If not, I think it would make sense to align it with the "standard". I sure tripped over this  :-)

Cheers,
Daniel

**Comment by cherouvim** [comment]
Would a configuration for switching these around in QUnit.config make sense?

**Comment by leobalter** [comment]
@cherouvim probably not, the idea is to have the API remaining simple and consistent, in a way it's easy to work with QUnit on any project.

**Comment by cherouvim** [comment]
I agree with that mentality. The problem is that moving over from JUnit the assertions are a bit confusing. Not a showstopper though.

**Comment by FagnerMartinsBrack** [comment]
The only problem with this is [when using constants](https://github.com/jquery/jquery/commit/d3d8d9751f3d14a545b26cf820dc1f51896a7b50). So, to prevent a "[boolean-trap](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html)-like" problem, one can always use the "Assertion Declaration Pattern" (yeah I just made that up):

```javascript
var expected = 5;
var actual = parseInt( "5" );
assert.strictEqual( actual, expected );
```
