### ISSUE TITLE
QUnit.diff should be given dumped values before html escape

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#483]
The parameters can be serialised by jsDump, but they shouldn't be escaped yet so that a diff library can diff the real values instead of something that is already harder to work with.

Afaik nothing relies on this, we should be able to move the `escapeText` call from around the values from jsDump to around the `diff()` call.

**Comment by shivamdixit** [comment]
@Krinkle If we move the `escapeText` call around the `diff()` call then the `<del>` and `<ins>` tags of diff are also escaped, because of which the output is all garbled.

**Comment by jzaefferer** [comment]
@shivamdixit we should evaluate this issue in the context of using goodle-diff-patch-match (#772), since we're very likely moving to that diff implementation.

**Comment by shivamdixit** [comment]
Yup, I evaluated this issue in the context of using google-diff-patch-match library only.

**Comment by jzaefferer** [comment]
Okay. Not sure if we still need this issue, might be invalid in this context. I'll leave it open for now, maybe @Krinkle can chime in. Let's focus on other issues until then.
