### ISSUE TITLE
Standard reporter interface

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunit#531]
We want to provide a reporter interface that we can share with other testing tools like Jasmine and Mocha, to make it easier for integration tools - like Karma, browserstack-runner, grunt plugins - to hook into QUnit and other tools. Anyone writing a new JavaScript testing tool should be encouraged to provide the same interface, making it more reasonable to support these tools.

This requires a bunch of research. So far we identified two components that need to be standardised:
- needs a data format ala JUnit XML (here's an [unofficial xsd to validate the output](https://github.com/ygjb/XmlUnit/blob/master/JUnit.xsd)) or [TAP](http://testanything.org/tap-specification.html), that is flexible enough to support QUnit and others. Specifically, Jasmine and other BDD styles support (more or less) infinite nesting, which QUnit doesn't
- need a list of events that provide this data. Something like `done` should provide the full datastructure, other events should help to output progress

Related tickets:
- (#351) testDone should provide aggregated assertion results
- (#405) Implement reporter interface
- (#422) Implement QUnit callbacks event listener style
- (#472) QUnit.done should provide aggregated results

**Comment by asped08** [comment]
Gsoc 2015 - 

I am interested in this project idea. but I cant understand this and how to work. Any help or references would be great.

**Comment by jzaefferer** [comment]
@asped08 you should check out https://github.com/js-reporters/js-reporters - starting with the readme there, then going into the open issues, there's plenty to read.

**Comment by jzaefferer** [comment]
Based on a discussion on IRC about "why would a reporter consume TAP?", I think there are multiple scenarios that we should at least consider. For QUnit we currently have a pretty simple model for just one abstraction layer:

```
Runner -> Reporter
```

Runner runs tests, reporter registers event handlers to output result, usually via HTML reporter in the browser, but could also be on CLI etc.

When running tests in CI envs, the often an intermediate data format that is picked up by something else:

```
Runner -> Data -> Reporter
```

Here the runner could write JUnit XML to disk, which then is picked up by a Jenkins plugin that visulizes test failures over time. Instead of xml, this could also use TAP. Instead of a Jenkins plugin, this could get visualized using a HTML reporter. In that case, we'd have TAP fed into a reporter.

The jsreporter project is currently mostly about the runner interface that provides the data in the first place. That's an important aspect and worth focusing on. It would also be great to do research on other data formats and interchangable reporters (e.g. around [`node-tap`](https://github.com/isaacs/node-tap)).

**Comment by fcarstens** [comment]
Thanks for the clarification! 
Looking at @JamesMGreene's work, wouldn't it be something like 
```
Runner -> Standardized Data/Interface -> TAP-Reporter -> consumer (e.g. Jenkins)
```
My point on IRC was that the TAP-Reporter would be one of the (interchangeable) reporters, as in  http://mochajs.org/#tap-reporter and not directly part of the standardized interface.

**Comment by jzaefferer** [comment]
Yes, I agree, that's a better description.

**Comment by leobalter** [comment]
We're definitely using js-reporters as our standard reporter interface.
