### ISSUE TITLE
Support source maps (Browserify)

### ISSUE THREAD

**Issue by vahdani** [qunitjs/qunit#590]
When using a build tool like Browserify, it's required to build a bundle even on development. In this environment QUnit will show the line numbers according to the build file which is confusing.
It would be great if QUnit could parse the related source map and reference real source files when an error occurs.

**Comment by simonzack** [comment]
+1, I would also love source maps, which are generated by traceur in my case.

**Comment by mightyiam** [comment]
:+1:

I'm transitioning [WYMeditor](https://github.com/wymeditor/wymeditor) to CommonJS with Browserify and I'm seeing this dreadfully unhelpful thing.
![screenshot_2015-09-20_16-05-25](https://cloud.githubusercontent.com/assets/635591/9980863/6ce2b6e8-5fb1-11e5-97bf-e8ceb7cd9fe4.png)

**Comment by jzaefferer** [comment]
Once a library like [TraceKit supports this](https://github.com/csnover/TraceKit/issues/31), we can look into adopting it. If you want to help, look into integration of TraceKit into QUnit. Otherwise this will probably stay open for another year or two.

**Comment by DrewML** [comment]
For anyone still looking for this support, you can essentially hack it yourself using the browser build of [node-source-map-support](https://github.com/evanw/node-source-map-support#browser-support). Note that it will only work in browsers whose `Error` objects include a `stack` property.

**Comment by Krinkle** [comment]
I've confirmed that Node's built-in support for source maps (Node 14+) works fine with QUnit. This is now validated through an integration test in our CI, and documented at <https://qunitjs.com/cli/#nodejs-cli-options>.

For the browser, I would recommend using the browser's own dev tools. You can use these by ticking the "No try-catch" checkbox in the QUnit browser interface. This will allow you to get regular dev tooling going based on uncaught exceptions.

I filed https://github.com/qunitjs/qunitjs.com/issues/157 to write this down on the site as well.
