### ISSUE TITLE
Allow calling test() from within loop.

### ISSUE THREAD

**Issue by kasbah** [qunitjs/qunit#606]
If you want to generate tests in a loop only one of the will pass the internal validTest() function.

Why not allow creation of tests like this?

```
  var a, item, i, len;

  a = [1, 2, 3];

  for (i = 0, len = a.length; i < len; i++) {
    item = a[i];
    QUnit.test("Generated " + item, function() {
      ok(true);
    });
  }
```

**Comment by jangreis** [comment]
I'm having the same issue. The above code works but if you try to access item inside the test, it will always be equal to 3. It seems like the loop runs through all iterations and only then is the test called three times...

**Comment by leobalter** [comment]
@jangreis that's a bad use on the for loop not defining a block scoped variable. If possible, try using a .forEach or even `let/const` inside the for loop block if you have it available.

**Comment by trentmwillis** [comment]
@jangreis this is because the test callbacks aren't run synchronously. So the behavior you're seeing is correct. For more info, including possible patterns to fix the problem, [check out this SO question](http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example).

**Comment by jangreis** [comment]
Thanks a lot, both of you. I'm still coming to terms with scoping in JS :-)
I used a for (let ...) loop now and it looks like it all works fine. Thank you for your rapid responses.

**Comment by michange** [comment]
The other issue I would see with such generated Qunit.test() calls is that it seems one can't rerun those selectively with the Qunit reload-based 'rerun' links. 
Is there any pattern to leverage those default Qunit links with generated tests ?
