### ISSUE TITLE
propEqual for TypedArrays (was deepEqual for TypeArrays)

### ISSUE THREAD

**Issue by fernandojsg** [qunitjs/qunit#672]
I've notice that qunit gives incorrect results when using typedArrays (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays).
I think it will be a great improvement if it will let you compare standard array and typedarrays like for example:

``` javascript
var ta = new Uint8Array(4);
deepEqual(ta, [0, 0, 0, 0], "Typed array and array equals");
```

I was checking the code and I guess one solution could be to change `core.js`, in the line when you know that the typeof is an `object`, and do something like:

``` javascript
...
if ( typeof obj === "object" ) {
    if ( obj instanceof Int8Array ||
        obj instanceof Uint8Array ||
        obj instanceof Uint8ClampedArray ||
        obj instanceof Int16Array ||
        obj instanceof Uint16Array ||
        obj instanceof Int32Array ||
        obj instanceof Uint32Array ||
        obj instanceof Float32Array ||
        obj instanceof Float64Array ) {
        return "typedarray";
    }
    return "object";
}
```

And then on `equiv.js` returns a new function for the new type.

**Comment by shivamdixit** [comment]
Hey @fernandojsg, are you still working on it?

**Comment by jzaefferer** [comment]
@shivamdixit I don't think they're still working on this, you're welcome to look into this and send a PR.

**Comment by jzaefferer** [comment]
Considering that `deepEqual` generally takes the constructor into account (while `propEqual` doesn't), I wonder if we should actually leave `deepEqual` as-is and adjust `propEqual` instead to deal with this. Any opinions? Would be good to figure that out soon, since #783 provides a PR for the behaviour that was discussed so far.

**Comment by shivamdixit** [comment]
I think it's a good idea to adjust `propEqual` instead of `deepEqual`.

**Comment by jzaefferer** [comment]
@fernandojsg @leobalter @JamesMGreene any thoughts on the suggestion above?

**Comment by leobalter** [comment]
> leave deepEqual as-is and adjust propEqual

seems good for consistency. Need to check any possible breaking change.

**Comment by trentmwillis** [comment]
Closing this in favor of discussion continuing in https://github.com/qunitjs/qunit/issues/1114.
