### ISSUE TITLE
Use jquery-release changelog, integrate into build/release.js

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunit#736]
Currently we use `git changelog` via git-extras, which doesn't work that well anymore and has no ticket or commit references. Updating that manually is annoying, too. Would make future releases easier to integrate the changelog generated by jquery-release into our custom release, somewhere prepending it to History.md, or just removing that file and only using the generated changelog on the repo's release page.

**Comment by platinumazure** [comment]
@jzaefferer @leobalter Is this issue still valid, given the existence of #1073?

**Comment by Krinkle** [comment]
Closing in favour of #1073.
