### ISSUE TITLE
Support multi-tenant manual test start 

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#840]
See karma-runner/karma-qunit#27 for an example of such issue.

I propose we add a method that instead of starting the test suite, takes a Promise that will be waited on before the tests start. And there can be any number of promises provided to this method.

Crucial too is that it is allowed to provide additional promises at any time before all known promises are fulfilled. (e.g. adding A and B, B is resolved, A is pending and during A, a C is encountered; as would commonly be the case when loading code in multiple stages, e.g. Karma loading the user code and marking its own area as fulfilled).

Proposed interface:

``` js
QUnit.delayStart( Promise thenable );
```

Proposed implementation:

When called, this will (if not already) set `config.autostart = false;`, and add the promise to an internal list. When the promise is resolved or rejected, it will remove itself from said internal list at look at the length of the list. If it is now empty, call `QUnit.start()`. If not, wait for another promise to be fulfilled which will naturally result in another check of the remaining promises.

**Comment by jzaefferer** [comment]
This seems reasonable. It sounds like it shouldn't be too complicated to implement.

One thing that is unclear to me: How does it related to existing APIs? Would it replace anything? Or just be an optional API on top of `config.autostart = false` and `QUnit.start()`?

**Comment by Krinkle** [comment]
@jzaefferer I'm not sure yet but I'm thinking it would be best implemented underneath the existing API. Then re-implement the static/global `config.autostart` and `QUnit.start()` functionality on top of this new API as consumer in e.g. `QUnit.load`.

**Comment by S4NT14G0** [comment]
Has this issue ever been fixed?  I trying to run karma and qunit.  I need to wait for asynchronous data to load before my tests begin and karma is giving me an error:

"Executed 0 of 0 ERROR"

**Comment by Krinkle** [comment]
@S4NT14G0 As mentioned, the easiest fix is simply to set `QUnit.config.autostart = false;` from a regular script file that you load, and then call `QUnit.start()` when you're ready.

**Comment by platinumazure** [comment]
@Krinkle Do you believe this issue needs to remain open, or can we close with that resolution?
