### ISSUE TITLE
Allow chai usage integration.

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#864]
I'm thinking about creating a assert adaptor to allow the use of custom assertion libs, as Chai.

To start I thinking on something like:

``` js
QUnit.config.assert = "chai";

or

QUnit.setup({
  assert: "chai",
  reporter: "HTML"
});
```

I know `QUnit.setup` is not even in the plans, this is something to maybe discuss in another issue.

Possible drawbacks: having chai plugged in, QUnit would probably break a test on its first failing assertion, but wouldn't fail without a builtin assertion call, along with the expect method.

Probably, the necessary steps to implement this is:
- avoid QUnit tests failing without any of its builtin assertions call.
- catch chai thrown errors from the assertions and report it as failing
- a test without any failing assertion should pass (that's silly, but...)

Maybe we can register the chai assertions calls, worth investigate: https://github.com/chaijs/chai/blob/master/lib/chai/assertion.js#L99-L113

---

Extra: this could be extended to node's assert module as well.

**Comment by jzaefferer** [comment]
Might be possible to wrap each assertion to catch the AssertionError and pass it through to `pushFailure`, including the stack.

Supporting node's assert module also sounds interesting.

**Comment by Krinkle** [comment]
I think QUnit is and should remain primarily an assertion library with a bult-in test runner. We do support plugging in reporters and output formatters, but the test input are part of QUnit's simplicity.

If there are particular assertions difficult to do, I think we should improve QUnit itself. Although I do note that QUnit supports assertion plugins, and I suppose one might want to be able to use Chai plugins through an adapter of sorts. I'd be happy to promote such plugin on the QUnit website!
