### ISSUE TITLE
Set QUnit config via function

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#872]
I would like to set QUnit.config settings through a function call, like:

``` js
QUnit.config( {
  autorun: false,
  collapse: false,
  ...
} );

// or:
QUnit.setup( {
  autorun: false,
  collapse: false,
  ...
} );

// or even:
QUnit.config.set( {
  autorun: false,
  collapse: false,
  ...
} );
```

This way we can make a better handle for other options, like setting a custom reporter like:

``` js
QUnit.config( {
  // please not this issue won't define the reporter settings.
  reporter: "tap",
  reporterOptions: {
    outputMethod: console.log
  }
} );
```

This also allows settings definitions through a json file, imported and applied to QUnit.config.

---

If this is not possible I would have to set the custom reporter (and maybe other features in the future)  through a direct function like: `QUnit.config.reporter( "tap", { options } );`

**Comment by jzaefferer** [comment]
I don't quite understand the usecase. The reporter example seems easy enough to accomplish using the current approach, without adding anything new.

"How to register reporters" is an interesting question though. We should look at options for that first.

**Comment by leobalter** [comment]
I don't think this is necessary to change anymore.
