### ISSUE TITLE
Throw warnings for deprecated features.

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#881]
QUnit should throw warnings (reporter/console) for deprecated features, including:
- use of global methods instead of the namespaced methods. (some can be easily fixed with local variables like: `var test = QUnit.test;`)
- use of stop/start methods
- etc

Also it should mention the qunit-migrate tools.

**Comment by jzaefferer** [comment]
I don't think we need an additional migration layer. 2.0 will throw helpful errors for removed features, for anything not yet migrated.

**Comment by leobalter** [comment]
Having warnings for deprecated features on 1.x helps on the migration process, so a run using the last 1.x without any warnings would result on a safe and clean migration to 2.0

**Comment by leobalter** [comment]
After talking on a meeting today with @jzaefferer, we decided to keep this issue and land it before QUnit 2.0

**Comment by jzaefferer** [comment]
There should be an option to disable the warnings. For example, in jQuery UI there's the $.uiBackCompat` flag, which turns off the back-compat layer, to test if the next release (where deprecated features are dropped) will still work. That's different from warnings, but we can do something similar here.

**Comment by jzaefferer** [comment]
Is this still valid?

**Comment by leobalter** [comment]
not landing on 2.0 but useful to guide the Warnings API as the request is to get proper deprecation warning messages on the reporter, not only an exception pushing a failure, even if it's well handled by QUnit.

**Comment by trentmwillis** [comment]
I'm going to close this. We added `Logger.warn` internally for logging deprecations.
