### ISSUE TITLE
Add a Stop Execution button up top

### ISSUE THREAD

**Issue by tundal45** [qunitjs/qunit#928]
This might be just me but I feel that there are times where you want to run all the tests until their is a particular type of failure that you want to focus on. However, getting to that error to click rerun while the tests are running is impossible. So I was wondering if it would be useful to have a button that stops test execution and retains the results view up until that point.
1. Is this possible?
2. Will people who are not me find this useful?
3. Where should I begin (assuming 1 & to are affirmative)?

**Comment by trentmwillis** [comment]
In my personal experience, when dealing with a large test suite this is definitely desirable. Especially when dealing with debugging a flaky test that is dependent on test order.

I know Ember currently supports this with a [`pauseTest` helper that returns a non-resolving promise](http://emberjs.com/api/classes/Ember.Test.html#method_pauseTest), but this only works when invoked from within a test. I don't think it would be difficult to implement a similar feature that is invoked from the UI.

That said, we'd need to establish a more rigorous definition of what this behavior is: do we pause immediately or do we wait for the current test and associated hooks to finish? Do we allow tests to be unpaused? Will this pause count against the test suite's timeout limit?

**Comment by tundal45** [comment]
> do we pause immediately or do we wait for the current test and associated hooks to finish?

For now, I would be happy with a stop execution that just stops everything and the user can re-run the test if they want to. Maybe a pause could be implemented but I was envisioning the "simpler" just stop the world with this one.

**Comment by gibson042** [comment]
I could see doing this with something like `QUnit.config.queue.length = 0`, which would let the active test finish but abort all pending tests. The display elements would also need updating, e.g. to reveal the hidden `<li>` elements. PRs considered, I suppose.

**Comment by trentmwillis** [comment]
> I was envisioning the "simpler" just stop the world with this one.

Seems good to me. Depending on implementation, I don't think it would be hard to extend this to "pause" in the future.

> let the active test finish but abort all pending tests.

I think this makes the most sense as far as stopping behavior is concerned.

@tundal45 would you want to take a crack at implementing?

**Comment by tundal45** [comment]
@trentmwillis @gibson042 Yes, I can take a look.

**Comment by rwjblue** [comment]
I was just discussing this with @raytiley earlier this week.  I think this would be a wonderfully useful feature...

**Comment by trentmwillis** [comment]
@rwjblue / @raytiley PRs welcome 😃

**Comment by tundal45** [comment]
Yeah sorry I've not had a chance to look into this further. I'll see if I can squeeze in some time in the coming weeks. If someone else wants to do it before I get to it, that's great too!

**Comment by raytiley** [comment]
Looking into this now. Need to find my bearings in the repo.
