### ISSUE TITLE
Deprecate assert.push

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#986]
Please, see the comments below.

**Comment by jzaefferer** [comment]
Did you mistake `assert.push` for `QUnit.push`?

**Comment by leobalter** [comment]
_Mea culpa_, this was badly opened/explained. `QUnit.push` is already removed (with the deprecation message).

What I wanted is to remove `assert.push` which rethinking about it I guess we shouldn't do it in 2.0.

Instead, a warning for using this method is welcoming, suggesting `pushResult` should be used instead. It's too early to drop this method as that might cost extra work from any external assertion plugin.

With that said, this warning doesn't need to land with 2.0, but we can do it soon.

@trentmwillis I'm sorry for the extra work, thanks for the help.

**Comment by rdugue** [comment]
I made a pull request to address this, but I accidentally titled it with the branch wrong issue number.  Apologies... I can resubmit if necessary.
